import { syncSpec } from "../../../commands/sync.command.js";
import {
  acrCheckSpec,
  acrExplainSpec,
  acrGenerateSpec,
  acrSchemaSpec,
  acrSpec,
  acrValidateSpec,
} from "../../../commands/acr/acr.command.js";
import {
  evidenceBundleSpec,
  evidenceSpec,
  evidenceVerifySpec,
} from "../../../commands/evidence/evidence.command.js";
import {
  hermesDoctorSpec,
  hermesEnqueueSpec,
  hermesLifecycleSpec,
  hermesReconcileSpec,
  hermesSpec,
  hermesSuperviseSpec,
} from "../../../commands/hermes/hermes.command.js";
import {
  blueprintDriftSpec,
  blueprintExamplesSpec,
  blueprintExplainSpec,
  blueprintListSpec,
  blueprintReportSpec,
  blueprintSnapshotSpec,
  blueprintScaffoldSpec,
  blueprintSpec,
  blueprintValidateSpec,
} from "../../../commands/blueprint/blueprint.command.js";
import {
  blueprintsCatalogInfoSpec,
  blueprintsCatalogListSpec,
  blueprintsCatalogRefreshSpec,
  blueprintsCatalogSpec,
  blueprintsInstallSpec,
  blueprintsSpec,
} from "../../../commands/blueprints/blueprints.command.js";
import {
  backendInspectSpec,
  backendConnectSpec,
  backendMigrateCanonicalStateSpec,
  backendSpec,
  backendSyncSpec,
} from "../../../commands/backend/sync.command.js";
import {
  branchBaseClearSpec,
  branchBaseExplainSpec,
  branchBaseGetSpec,
  branchBaseSetSpec,
  branchBaseSpec,
} from "../../../commands/branch/base.command.js";
import { branchRemoveSpec } from "../../../commands/branch/remove.command.js";
import { branchStatusSpec } from "../../../commands/branch/status.command.js";
import { flowRepairSpec } from "../../../commands/flow/repair.command.js";
import { flowSpec } from "../../../commands/flow/flow.command.js";
import { workStartSpec } from "../../../commands/branch/work-start.command.js";
import { workResumeSpec } from "../../../commands/branch/work-resume.command.js";
import { integrateSpec } from "../../../commands/integrate.spec.js";
import {
  integrateQueueAdoptLegacyProtectedConflictSpec,
  integrateQueueClaimSpec,
  integrateQueueDoctorSpec,
  integrateQueueEnqueueSpec,
  integrateQueueListSpec,
  integrateQueueReleaseSpec,
  integrateQueueRunNextSpec,
  integrateQueueSpec,
} from "../../../commands/integrate-queue.spec.js";
import {
  prCheckSpec,
  prCloseSpec,
  prCloseSupersededSpec,
  prConflictReworkSpec,
  prFlowStatusSpec,
  prNoteSpec,
  prOpenSpec,
  prSpec,
  prUpdateSpec,
} from "../../../commands/pr/pr.spec.js";
import { recipesAddSpec } from "../../../commands/recipes/add.command.js";
import { recipesActiveSpec } from "../../../commands/recipes/active.command.js";
import { recipesCachePruneSpec } from "../../../commands/recipes/cache-prune.command.js";
import { recipesCacheSpec } from "../../../commands/recipes/cache.command.js";
import { recipesDetachSpec } from "../../../commands/recipes/detach.command.js";
import { recipesDisableSpec } from "../../../commands/recipes/disable.command.js";
import { recipesExplainSpec } from "../../../commands/recipes/explain.command.js";
import { recipesExplainActiveSpec } from "../../../commands/recipes/explain-active.command.js";
import { recipesEnableSpec } from "../../../commands/recipes/enable.command.js";
import { recipesInfoSpec } from "../../../commands/recipes/info.command.js";
import { recipesInstallSpec } from "../../../commands/recipes/install.spec.js";
import { recipesListRemoteSpec } from "../../../commands/recipes/list-remote.command.js";
import { recipesListSpec } from "../../../commands/recipes/list.command.js";
import { recipesRemoveSpec } from "../../../commands/recipes/remove.command.js";
import { recipesSpec } from "../../../commands/recipes/recipes.command.js";
import { recipesUpdateSpec } from "../../../commands/recipes/update.command.js";
import { contextIngestSpec } from "../../../commands/context/ingest.spec.js";
import {
  contextCapabilityDiscoverSpec,
  contextCapabilitySearchSpec,
  contextCapabilitySpec,
  contextCapabilityValidateSpec,
  contextDashboardSpec,
  contextDoctorSpec,
  contextFinalizeTaskSpec,
  contextExtractionApplySpec,
  contextSuperviseTaskSpec,
  contextGraphNeighborsSpec,
  contextGraphExportSpec,
  contextGraphShowSpec,
  contextGraphSpec,
  contextGraphSummarySpec,
  contextGraphValidateSpec,
  contextHarvestSpec,
  contextHarvestTasksSpec,
  contextInitSpec,
  contextMigrateSpec,
  contextReindexSpec,
  contextSearchSpec,
  contextShowSpec,
  contextSpec,
  contextVerifyTaskSpec,
  contextWikiExplainSpec,
  contextWikiIndexSpec,
  contextWikiLinkSpec,
  contextWikiLintSpec,
  contextWikiNewSpec,
  contextWikiReportSpec,
  contextWikiSpec,
} from "../../../commands/context/context.spec.js";
import {
  contextCheckSpec,
  contextLearnChangesSpec,
  contextLearnFilesSpec,
  contextLearnSpec,
  contextLearnTasksSpec,
} from "../../../commands/context/context.learn.spec.js";
import {
  evaluatorApplySpec,
  evaluatorExecuteSpec,
  evaluatorListSpec,
  evaluatorPrepareSpec,
  evaluatorRunSpec,
  evaluatorShowSpec,
  evaluatorSpec,
} from "../../../commands/evaluator/evaluator.command.js";

import {
  declareCommand,
  declareConditionalSessionCommand,
  declareSessionCommand,
  type CommandEntry,
} from "./kernel.js";
import {
  CONTEXT_PROJECT_REQUIREMENTS,
  CONTEXT_TASK_READ_REQUIREMENTS,
  CONTEXT_TASK_WRITE_REQUIREMENTS,
  EVALUATOR_EXECUTE_REQUIREMENTS,
  EVALUATOR_PREPARE_REQUIREMENTS,
  EVALUATOR_WRITE_REQUIREMENTS,
} from "./context-evaluator-capability-profiles.js";
import { NO_CONTEXT_REQUIREMENTS } from "./project-capability-profiles.js";
import {
  fromCommandsRecipesRecipesCommand,
  fromCommandsRecipesCacheCommand,
  fromCommandsRecipesAddCommand,
  fromCommandsRecipesListCommand,
  fromCommandsRecipesListRemoteCommand,
  fromCommandsRecipesExplainCommand,
  fromCommandsRecipesEnableCommand,
  fromCommandsRecipesRemoveCommand,
  fromCommandsRecipesDetachCommand,
  fromCommandsRecipesInstallRun,
  fromCommandsBranchBaseCommand,
  fromCommandsBranchStatusCommand,
  loadWorkStartSpec,
  loadWorkResumeSpec,
  fromRecipesActiveSpec,
  fromRecipesInfoSpec,
  loadRecipesExplainActiveSpec,
  fromRecipesDisableSpec,
  fromRecipesUpdateSpec,
  fromRecipesCachePruneSpec,
  fromBranchBaseSetSpec,
  fromBranchBaseExplainSpec,
  fromBranchRemoveSpec,
  loadBackendSpec,
  loadBackendSyncSpec,
  loadBackendInspectSpec,
  loadBackendConnectSpec,
  loadBackendMigrateCanonicalStateSpec,
  loadSyncSpec,
  loadPrSpec,
  loadPrOpenSpec,
  loadPrUpdateSpec,
  loadPrCheckSpec,
  loadPrConflictReworkSpec,
  loadPrCloseSpec,
  loadPrCloseSupersededSpec,
  loadPrFlowStatusSpec,
  loadPrNoteSpec,
  fromCommandsFlowCommand,
  loadFlowRepairSpec,
  loadIntegrateSpec,
  loadIntegrateQueueSpec,
  loadIntegrateQueueEnqueueSpec,
  loadIntegrateQueueListSpec,
  loadIntegrateQueueClaimSpec,
  loadIntegrateQueueDoctorSpec,
  loadIntegrateQueueAdoptLegacyProtectedConflictSpec,
  loadIntegrateQueueReleaseSpec,
  loadIntegrateQueueRunNextSpec,
  loadAcrSpec,
  loadAcrSchemaSpec,
  loadAcrGenerateSpec,
  loadAcrValidateSpec,
  loadAcrCheckSpec,
  loadAcrExplainSpec,
  fromCommandsEvidenceCommand,
  loadEvidenceBundleSpec,
  loadEvidenceVerifySpec,
  fromCommandsHermesCommand,
  loadHermesDoctorSpec,
  loadHermesEnqueueSpec,
  loadHermesLifecycleSpec,
  loadHermesReconcileSpec,
  loadHermesSuperviseSpec,
  loadBlueprintSpec,
  loadBlueprintListSpec,
  loadBlueprintExamplesSpec,
  loadBlueprintDriftSpec,
  loadBlueprintExplainSpec,
  loadBlueprintSnapshotSpec,
  loadBlueprintReportSpec,
  loadBlueprintValidateSpec,
  loadBlueprintScaffoldSpec,
  loadEvaluatorSpec,
  loadEvaluatorListSpec,
  loadEvaluatorShowSpec,
  loadEvaluatorPrepareSpec,
  loadEvaluatorApplySpec,
  loadEvaluatorExecuteSpec,
  loadEvaluatorRunPrepareSpec,
  loadEvaluatorRunWriteSpec,
  fromCommandsBlueprintsCommand,
  loadContextIngestSpec,
  loadContextGroupSpec,
  loadContextInitSpec,
  loadContextLearnGroupSpec,
  loadContextWikiGroupSpec,
  loadContextHarvestGroupSpec,
  loadContextGraphGroupSpec,
  loadContextCapabilityGroupSpec,
  loadContextMigrateSpec,
  loadContextCheckSpec,
  loadContextReindexSpec,
  loadContextSearchSpec,
  loadContextDashboardSpec,
  loadContextShowSpec,
  loadContextWikiNewSpec,
  loadContextWikiLintSpec,
  loadContextWikiExplainSpec,
  loadContextWikiLinkSpec,
  loadContextWikiIndexSpec,
  loadContextWikiReportSpec,
  loadContextDoctorSpec,
  loadContextFinalizeTaskSpec,
  loadContextVerifyTaskSpec,
  loadContextGraphSummarySpec,
  loadContextGraphShowSpec,
  loadContextGraphNeighborsSpec,
  loadContextGraphValidateSpec,
  loadContextGraphExportSpec,
  loadContextExtractionApplySpec,
  loadContextCapabilityValidateSpec,
  loadContextCapabilitySearchSpec,
  loadContextCapabilityDiscoverSpec,
  loadContextLearnFilesSpec,
  loadContextLearnChangesSpec,
  loadContextLearnTasksSpec,
  loadContextHarvestTasksSpec,
  loadContextSuperviseTaskSpec,
} from "../command-loaders/project.js";

export const PROJECT_COMMANDS = [
  declareCommand(acrSpec, { load: loadAcrSpec, needs: "none" }),
  declareCommand(acrSchemaSpec, { load: loadAcrSchemaSpec, needs: "none" }),
  declareCommand(acrGenerateSpec, { load: loadAcrGenerateSpec }),
  declareCommand(acrValidateSpec, { load: loadAcrValidateSpec }),
  declareCommand(acrCheckSpec, { load: loadAcrCheckSpec }),
  declareCommand(acrExplainSpec, { load: loadAcrExplainSpec }),
  fromCommandsEvidenceCommand(evidenceSpec, "runEvidenceGroup", { needs: "none" }),
  declareCommand(evidenceBundleSpec, { load: loadEvidenceBundleSpec }),
  declareCommand(evidenceVerifySpec, { load: loadEvidenceVerifySpec }),
  fromCommandsHermesCommand(hermesSpec, "runHermesGroup"),
  declareCommand(hermesEnqueueSpec, { load: loadHermesEnqueueSpec }),
  declareCommand(hermesSuperviseSpec, { load: loadHermesSuperviseSpec }),
  declareCommand(hermesReconcileSpec, { load: loadHermesReconcileSpec }),
  declareCommand(hermesLifecycleSpec, { load: loadHermesLifecycleSpec }),
  declareCommand(hermesDoctorSpec, { load: loadHermesDoctorSpec }),
  declareCommand(blueprintSpec, { load: loadBlueprintSpec, needs: "none" }),
  declareCommand(blueprintListSpec, { load: loadBlueprintListSpec, needs: "none" }),
  declareCommand(blueprintExamplesSpec, { load: loadBlueprintExamplesSpec, needs: "none" }),
  declareCommand(blueprintExplainSpec, { load: loadBlueprintExplainSpec }),
  declareCommand(blueprintSnapshotSpec, { load: loadBlueprintSnapshotSpec }),
  declareCommand(blueprintDriftSpec, { load: loadBlueprintDriftSpec }),
  declareCommand(blueprintReportSpec, { load: loadBlueprintReportSpec, needs: "none" }),
  declareCommand(blueprintScaffoldSpec, { load: loadBlueprintScaffoldSpec, needs: "none" }),
  declareCommand(blueprintValidateSpec, { load: loadBlueprintValidateSpec, needs: "none" }),
  declareSessionCommand(evaluatorSpec, {
    load: loadEvaluatorSpec,
    requirements: NO_CONTEXT_REQUIREMENTS,
  }),
  declareSessionCommand(evaluatorListSpec, {
    load: loadEvaluatorListSpec,
    requirements: NO_CONTEXT_REQUIREMENTS,
  }),
  declareSessionCommand(evaluatorShowSpec, {
    load: loadEvaluatorShowSpec,
    requirements: NO_CONTEXT_REQUIREMENTS,
  }),
  declareSessionCommand(evaluatorPrepareSpec, {
    load: loadEvaluatorPrepareSpec,
    requirements: EVALUATOR_PREPARE_REQUIREMENTS,
  }),
  declareSessionCommand(evaluatorApplySpec, {
    load: loadEvaluatorApplySpec,
    requirements: EVALUATOR_WRITE_REQUIREMENTS,
  }),
  declareSessionCommand(evaluatorExecuteSpec, {
    load: loadEvaluatorExecuteSpec,
    requirements: EVALUATOR_EXECUTE_REQUIREMENTS,
  }),
  declareConditionalSessionCommand(evaluatorRunSpec, {
    default: {
      load: loadEvaluatorRunPrepareSpec,
      requirements: EVALUATOR_PREPARE_REQUIREMENTS,
    },
    selected: {
      when: (parsed) => parsed.record,
      load: loadEvaluatorRunWriteSpec,
      requirements: EVALUATOR_WRITE_REQUIREMENTS,
    },
  }),
  fromCommandsBlueprintsCommand(blueprintsSpec, "runBlueprints", { needs: "none" }),
  fromCommandsBlueprintsCommand(blueprintsCatalogSpec, "runBlueprintsCatalog", { needs: "none" }),
  fromCommandsBlueprintsCommand(blueprintsCatalogRefreshSpec, "runBlueprintsCatalogRefresh", {
    needs: "none",
  }),
  fromCommandsBlueprintsCommand(blueprintsCatalogListSpec, "runBlueprintsCatalogList", {
    needs: "none",
  }),
  fromCommandsBlueprintsCommand(blueprintsCatalogInfoSpec, "runBlueprintsCatalogInfo", {
    needs: "none",
  }),
  fromCommandsBlueprintsCommand(blueprintsInstallSpec, "runBlueprintsInstall", {}),
  declareCommand(workStartSpec, { load: loadWorkStartSpec }),
  declareCommand(workResumeSpec, { load: loadWorkResumeSpec }),
  fromCommandsFlowCommand(flowSpec, "runFlow", { needs: "none" }),
  declareCommand(flowRepairSpec, { load: loadFlowRepairSpec }),
  fromCommandsRecipesRecipesCommand(recipesSpec, "runRecipes", { needs: "none" }),
  fromCommandsRecipesCacheCommand(recipesCacheSpec, "runRecipesCache", { needs: "none" }),
  fromCommandsRecipesAddCommand(recipesAddSpec, "runRecipesAdd", {}),
  fromRecipesActiveSpec(recipesActiveSpec, "runRecipesActive"),
  fromCommandsRecipesListCommand(recipesListSpec, "runRecipesList", { needs: "none" }),
  fromCommandsRecipesListRemoteCommand(recipesListRemoteSpec, "runRecipesListRemote", {}),
  fromRecipesInfoSpec(recipesInfoSpec, "runRecipesInfo", { needs: "none" }),
  fromCommandsRecipesExplainCommand(recipesExplainSpec, "runRecipesExplain", {}),
  declareCommand(recipesExplainActiveSpec, { load: loadRecipesExplainActiveSpec }),
  fromCommandsRecipesEnableCommand(recipesEnableSpec, "runRecipesEnable", {}),
  fromRecipesDisableSpec(recipesDisableSpec, "runRecipesDisable"),
  fromCommandsRecipesRemoveCommand(recipesRemoveSpec, "runRecipesRemove", {}),
  fromRecipesUpdateSpec(recipesUpdateSpec, "runRecipesUpdate"),
  fromCommandsRecipesDetachCommand(recipesDetachSpec, "runRecipesDetach", {}),
  fromRecipesCachePruneSpec(recipesCachePruneSpec, "runRecipesCachePrune"),
  fromCommandsRecipesInstallRun(recipesInstallSpec, "runRecipesInstall", { needs: "none" }),
  declareSessionCommand(contextSpec, {
    load: loadContextGroupSpec,
    requirements: NO_CONTEXT_REQUIREMENTS,
  }),
  declareSessionCommand(contextIngestSpec, {
    load: loadContextIngestSpec,
    requirements: CONTEXT_TASK_WRITE_REQUIREMENTS,
    surface: "advanced",
  }),
  declareSessionCommand(contextInitSpec, {
    load: loadContextInitSpec,
    requirements: NO_CONTEXT_REQUIREMENTS,
  }),
  declareSessionCommand(contextMigrateSpec, {
    load: loadContextMigrateSpec,
    requirements: CONTEXT_PROJECT_REQUIREMENTS,
    surface: "advanced",
  }),
  declareSessionCommand(contextLearnSpec, {
    load: loadContextLearnGroupSpec,
    requirements: NO_CONTEXT_REQUIREMENTS,
  }),
  declareSessionCommand(contextLearnFilesSpec, {
    load: loadContextLearnFilesSpec,
    requirements: CONTEXT_TASK_WRITE_REQUIREMENTS,
  }),
  declareSessionCommand(contextLearnChangesSpec, {
    load: loadContextLearnChangesSpec,
    requirements: CONTEXT_TASK_WRITE_REQUIREMENTS,
  }),
  declareSessionCommand(contextLearnTasksSpec, {
    load: loadContextLearnTasksSpec,
    requirements: CONTEXT_TASK_WRITE_REQUIREMENTS,
  }),
  declareSessionCommand(contextCheckSpec, {
    load: loadContextCheckSpec,
    requirements: CONTEXT_PROJECT_REQUIREMENTS,
  }),
  declareSessionCommand(contextReindexSpec, {
    load: loadContextReindexSpec,
    requirements: CONTEXT_PROJECT_REQUIREMENTS,
    surface: "advanced",
  }),
  declareSessionCommand(contextSearchSpec, {
    load: loadContextSearchSpec,
    requirements: CONTEXT_PROJECT_REQUIREMENTS,
  }),
  declareSessionCommand(contextDashboardSpec, {
    load: loadContextDashboardSpec,
    requirements: CONTEXT_PROJECT_REQUIREMENTS,
  }),
  declareSessionCommand(contextShowSpec, {
    load: loadContextShowSpec,
    requirements: CONTEXT_PROJECT_REQUIREMENTS,
  }),
  declareSessionCommand(contextWikiSpec, {
    load: loadContextWikiGroupSpec,
    requirements: NO_CONTEXT_REQUIREMENTS,
  }),
  declareSessionCommand(contextWikiNewSpec, {
    load: loadContextWikiNewSpec,
    requirements: CONTEXT_PROJECT_REQUIREMENTS,
  }),
  declareSessionCommand(contextWikiLintSpec, {
    load: loadContextWikiLintSpec,
    requirements: CONTEXT_PROJECT_REQUIREMENTS,
  }),
  declareSessionCommand(contextWikiExplainSpec, {
    load: loadContextWikiExplainSpec,
    requirements: CONTEXT_PROJECT_REQUIREMENTS,
  }),
  declareSessionCommand(contextWikiLinkSpec, {
    load: loadContextWikiLinkSpec,
    requirements: CONTEXT_PROJECT_REQUIREMENTS,
  }),
  declareSessionCommand(contextWikiIndexSpec, {
    load: loadContextWikiIndexSpec,
    requirements: CONTEXT_PROJECT_REQUIREMENTS,
  }),
  declareSessionCommand(contextWikiReportSpec, {
    load: loadContextWikiReportSpec,
    requirements: CONTEXT_PROJECT_REQUIREMENTS,
  }),
  declareSessionCommand(contextDoctorSpec, {
    load: loadContextDoctorSpec,
    requirements: CONTEXT_PROJECT_REQUIREMENTS,
    surface: "advanced",
  }),
  declareSessionCommand(contextFinalizeTaskSpec, {
    load: loadContextFinalizeTaskSpec,
    requirements: CONTEXT_TASK_WRITE_REQUIREMENTS,
  }),
  declareSessionCommand(contextSuperviseTaskSpec, {
    load: loadContextSuperviseTaskSpec,
    requirements: CONTEXT_TASK_WRITE_REQUIREMENTS,
  }),
  declareSessionCommand(contextVerifyTaskSpec, {
    load: loadContextVerifyTaskSpec,
    requirements: CONTEXT_TASK_READ_REQUIREMENTS,
    surface: "advanced",
  }),
  declareSessionCommand(contextHarvestSpec, {
    load: loadContextHarvestGroupSpec,
    requirements: NO_CONTEXT_REQUIREMENTS,
    surface: "advanced",
  }),
  declareSessionCommand(contextHarvestTasksSpec, {
    load: loadContextHarvestTasksSpec,
    requirements: CONTEXT_TASK_WRITE_REQUIREMENTS,
    surface: "advanced",
  }),
  declareSessionCommand(contextGraphSpec, {
    load: loadContextGraphGroupSpec,
    requirements: NO_CONTEXT_REQUIREMENTS,
    surface: "advanced",
  }),
  declareSessionCommand(contextGraphSummarySpec, {
    load: loadContextGraphSummarySpec,
    requirements: CONTEXT_PROJECT_REQUIREMENTS,
    surface: "advanced",
  }),
  declareSessionCommand(contextGraphShowSpec, {
    load: loadContextGraphShowSpec,
    requirements: CONTEXT_PROJECT_REQUIREMENTS,
    surface: "advanced",
  }),
  declareSessionCommand(contextGraphNeighborsSpec, {
    load: loadContextGraphNeighborsSpec,
    requirements: CONTEXT_PROJECT_REQUIREMENTS,
    surface: "advanced",
  }),
  declareSessionCommand(contextGraphValidateSpec, {
    load: loadContextGraphValidateSpec,
    requirements: CONTEXT_PROJECT_REQUIREMENTS,
    surface: "advanced",
  }),
  declareSessionCommand(contextGraphExportSpec, {
    load: loadContextGraphExportSpec,
    requirements: CONTEXT_PROJECT_REQUIREMENTS,
    surface: "advanced",
  }),
  declareSessionCommand(contextExtractionApplySpec, {
    load: loadContextExtractionApplySpec,
    requirements: CONTEXT_PROJECT_REQUIREMENTS,
    surface: "advanced",
  }),
  declareSessionCommand(contextCapabilitySpec, {
    load: loadContextCapabilityGroupSpec,
    requirements: NO_CONTEXT_REQUIREMENTS,
    surface: "advanced",
  }),
  declareSessionCommand(contextCapabilityValidateSpec, {
    load: loadContextCapabilityValidateSpec,
    requirements: CONTEXT_PROJECT_REQUIREMENTS,
    surface: "advanced",
  }),
  declareSessionCommand(contextCapabilitySearchSpec, {
    load: loadContextCapabilitySearchSpec,
    requirements: CONTEXT_PROJECT_REQUIREMENTS,
    surface: "advanced",
  }),
  declareSessionCommand(contextCapabilityDiscoverSpec, {
    load: loadContextCapabilityDiscoverSpec,
    requirements: CONTEXT_PROJECT_REQUIREMENTS,
    surface: "advanced",
  }),
  fromCommandsBranchBaseCommand(branchBaseSpec, "runBranchBase", { needs: "none" }),
  fromCommandsBranchBaseCommand(branchBaseGetSpec, "runBranchBaseGet", {}),
  fromBranchBaseSetSpec(branchBaseSetSpec, "runBranchBaseSet"),
  fromCommandsBranchBaseCommand(branchBaseClearSpec, "runBranchBaseClear", {}),
  fromBranchBaseExplainSpec(branchBaseExplainSpec, "runBranchBaseExplain"),
  fromCommandsBranchStatusCommand(branchStatusSpec, "runBranchStatus", {}),
  fromBranchRemoveSpec(branchRemoveSpec, "runBranchRemove"),
  declareCommand(backendSpec, { load: loadBackendSpec, needs: "none" }),
  declareCommand(backendSyncSpec, { load: loadBackendSyncSpec }),
  declareCommand(backendInspectSpec, { load: loadBackendInspectSpec }),
  declareCommand(backendConnectSpec, { load: loadBackendConnectSpec }),
  declareCommand(backendMigrateCanonicalStateSpec, {
    load: loadBackendMigrateCanonicalStateSpec,
    surface: "internal",
    helpGroup: "Maintenance",
  }),
  declareCommand(syncSpec, { load: loadSyncSpec }),
  declareCommand(prSpec, { load: loadPrSpec, needs: "none" }),
  declareCommand(prOpenSpec, { load: loadPrOpenSpec }),
  declareCommand(prUpdateSpec, { load: loadPrUpdateSpec }),
  declareSessionCommand(prCheckSpec, {
    load: loadPrCheckSpec,
    requirements: [
      "project",
      "config",
      "backend.read",
      "task.read",
      "git.head",
      "git.diff",
      "route.remote",
      "policy",
      "approvals",
      "provider",
    ],
  }),
  declareCommand(prConflictReworkSpec, { load: loadPrConflictReworkSpec }),
  declareCommand(prFlowStatusSpec, { load: loadPrFlowStatusSpec }),
  declareCommand(prCloseSpec, { load: loadPrCloseSpec }),
  declareCommand(prCloseSupersededSpec, { load: loadPrCloseSupersededSpec }),
  declareCommand(prNoteSpec, { load: loadPrNoteSpec }),
  declareCommand(integrateSpec, { load: loadIntegrateSpec }),
  declareCommand(integrateQueueSpec, { load: loadIntegrateQueueSpec, needs: "none" }),
  declareCommand(integrateQueueEnqueueSpec, { load: loadIntegrateQueueEnqueueSpec }),
  declareCommand(integrateQueueListSpec, { load: loadIntegrateQueueListSpec }),
  declareCommand(integrateQueueDoctorSpec, { load: loadIntegrateQueueDoctorSpec }),
  declareCommand(integrateQueueClaimSpec, { load: loadIntegrateQueueClaimSpec }),
  declareCommand(integrateQueueReleaseSpec, { load: loadIntegrateQueueReleaseSpec }),
  declareCommand(integrateQueueAdoptLegacyProtectedConflictSpec, {
    load: loadIntegrateQueueAdoptLegacyProtectedConflictSpec,
  }),
  declareCommand(integrateQueueRunNextSpec, { load: loadIntegrateQueueRunNextSpec }),
] as const satisfies readonly CommandEntry[];
