import type { LoopSpec } from "./model.js";

const COMMON_OUTPUTS = [
  "loop-run.json",
  "events.jsonl",
  "state.json",
  "iterations/<n>/decision.json",
] as const;

export const BUILTIN_LOOPS = [
  {
    schemaVersion: 1,
    id: "tdd.fix",
    version: "0.1.0",
    title: "TDD fix loop",
    description: "Patch a small behavior change through focused test feedback.",
    kind: "implementation",
    status: "experimental",
    appliesTo: {
      blueprints: ["code.direct", "code.branch_pr"],
      taskKinds: ["code"],
      taskTags: ["bug", "test", "tdd"],
      workflowModes: ["direct", "branch_pr"],
    },
    requires: { approvedPlan: true, verifyStepsPresent: true },
    permissions: {
      canEditFiles: true,
      canRunCommands: true,
      canOpenPr: false,
      canModifyPolicy: false,
      network: "disallowed",
    },
    budgets: { maxIterations: 5, maxWallTimeMinutes: 40, maxChangedFiles: 8, maxDiffLines: 500 },
    context: {
      include: ["task.intent", "task.approved_plan", "task.verify_steps", "git.diff"],
      exclude: ["secrets", "unrelated_raw_transcripts"],
    },
    steps: [
      { id: "load_context", type: "context.load" },
      { id: "render_prompt", type: "prompt.render", promptModule: "tdd.fix.implement" },
      { id: "agent_patch", type: "agent.run" },
      { id: "capture_diff", type: "git.diff" },
      { id: "focused_check", type: "check.run" },
      { id: "evaluator", type: "evaluator.run", evaluator: "recovery-context" },
    ],
    transitions: [
      {
        from: "evaluator",
        if: "checks.ok && evaluator.verdict == 'pass'",
        to: "finish",
        decision: "finish",
      },
      {
        from: "evaluator",
        if: "checks.failed && iteration < budgets.maxIterations",
        to: "render_prompt",
        decision: "retry_with_feedback",
        feedback: { include: ["checks.stderr", "evaluator.findings", "git.diff_summary"] },
      },
      { from: "evaluator", if: "budgets.exceeded", to: "blocked", decision: "block" },
    ],
    outputs: { required: COMMON_OUTPUTS },
    stopConditions: [
      { id: "success", reason: "Focused checks and evaluator pass.", decision: "finish" },
      { id: "max_iterations", reason: "Retry budget exhausted.", decision: "block" },
      {
        id: "no_test_surface",
        reason: "No runnable verification surface.",
        decision: "request_human_review",
      },
    ],
  },
  {
    schemaVersion: 1,
    id: "ci.repair",
    version: "0.1.0",
    title: "CI repair loop",
    description:
      "Classify a hosted check failure, reproduce locally when possible, and repair safely.",
    kind: "implementation",
    status: "experimental",
    appliesTo: {
      blueprints: ["code.branch_pr"],
      taskKinds: ["code"],
      taskTags: ["ci", "pr", "repair"],
      workflowModes: ["branch_pr"],
    },
    requires: { approvedPlan: true, hostedPr: true, ciFailure: true },
    permissions: {
      canEditFiles: true,
      canRunCommands: true,
      canOpenPr: false,
      network: "approval_required",
    },
    budgets: { maxIterations: 4, maxChangedFiles: 6, maxDiffLines: 400 },
    steps: [
      { id: "load_pr_state", type: "pr.check" },
      { id: "classify_failure", type: "evaluator.run", evaluator: "ci-failure-classifier" },
      { id: "render_prompt", type: "prompt.render", promptModule: "ci.repair" },
      { id: "agent_patch", type: "agent.run" },
      { id: "local_check", type: "check.run" },
      { id: "pr_update", type: "pr.update", when: "local_check.ok" },
      { id: "remote_check", type: "pr.wait_checks", when: "local_check.ok" },
    ],
    transitions: [
      { from: "remote_check", if: "remote_check.green", to: "finish", decision: "finish" },
      {
        from: "local_check",
        if: "local_check.failed && iteration < budgets.maxIterations",
        to: "render_prompt",
        decision: "retry_with_feedback",
      },
      {
        from: "classify_failure",
        if: "classify_failure.kind == 'infra'",
        to: "human_review",
        decision: "request_human_review",
      },
    ],
    outputs: { required: COMMON_OUTPUTS },
    stopConditions: [
      { id: "remote_green", reason: "Hosted checks are green.", decision: "finish" },
      {
        id: "infra_or_flake",
        reason: "Failure appears infra/flaky and needs human judgment.",
        decision: "request_human_review",
      },
    ],
  },
  {
    schemaVersion: 1,
    id: "docs.sync",
    version: "0.1.0",
    title: "Documentation sync loop",
    description: "Align documentation with source changes and verify docs surfaces.",
    kind: "implementation",
    status: "experimental",
    appliesTo: {
      blueprints: ["docs.change"],
      taskKinds: ["docs"],
      taskTags: ["docs"],
      workflowModes: ["direct", "branch_pr"],
    },
    requires: { approvedPlan: true },
    permissions: { canEditFiles: true, canRunCommands: true, canModifyPolicy: false },
    budgets: { maxIterations: 3, maxChangedFiles: 10, maxDiffLines: 700 },
    steps: [
      { id: "inspect_source", type: "context.load" },
      { id: "render_prompt", type: "prompt.render", promptModule: "docs.sync" },
      { id: "agent_docs_edit", type: "agent.run" },
      { id: "docs_build", type: "check.run" },
      { id: "evaluator", type: "evaluator.run", evaluator: "docs-source-alignment" },
    ],
    transitions: [
      {
        from: "evaluator",
        if: "docs_build.ok && evaluator.verdict == 'pass'",
        to: "finish",
        decision: "finish",
      },
      {
        from: "docs_build",
        if: "docs_build.failed && iteration < budgets.maxIterations",
        to: "render_prompt",
        decision: "retry_with_feedback",
      },
    ],
    outputs: { required: COMMON_OUTPUTS },
    stopConditions: [
      { id: "source_aligned", reason: "Docs check and source alignment pass.", decision: "finish" },
      {
        id: "product_positioning",
        reason: "Human product wording decision required.",
        decision: "request_human_review",
      },
    ],
  },
  {
    schemaVersion: 1,
    id: "security.review",
    version: "0.1.0",
    title: "Security review loop",
    description: "Review scoped security-sensitive changes without automatic patching.",
    kind: "review",
    status: "experimental",
    appliesTo: {
      taskKinds: ["code"],
      taskTags: ["security", "auth", "validation", "dependency"],
      workflowModes: ["direct", "branch_pr"],
    },
    permissions: {
      canEditFiles: false,
      canRunCommands: true,
      canModifyPolicy: false,
      network: "approval_required",
    },
    budgets: { maxIterations: 2 },
    steps: [
      { id: "load_policy", type: "context.load" },
      { id: "inspect_risk", type: "agent.review", promptModule: "security.review" },
      { id: "run_checks", type: "check.run", optional: true },
      { id: "evaluator", type: "evaluator.run", evaluator: "security-risk" },
    ],
    transitions: [
      { from: "evaluator", if: "evaluator.verdict == 'pass'", to: "finish", decision: "finish" },
      {
        from: "evaluator",
        if: "evaluator.verdict == 'findings'",
        to: "human_review",
        decision: "request_human_review",
      },
    ],
    outputs: { required: COMMON_OUTPUTS },
    stopConditions: [
      { id: "secrets_detected", reason: "Secret exposure or undefined scope.", decision: "block" },
      { id: "risk_accepted", reason: "Risk is low or accepted.", decision: "finish" },
    ],
  },
  {
    schemaVersion: 1,
    id: "context.harvest",
    version: "0.1.0",
    title: "Context harvest loop",
    description: "Extract reusable knowledge from completed task evidence for curator review.",
    kind: "context",
    status: "experimental",
    appliesTo: {
      taskKinds: ["context"],
      taskTags: ["context", "curator"],
      workflowModes: ["direct", "branch_pr"],
    },
    permissions: { canEditContext: "propose_only", canModifyCode: false, canModifyPolicy: false },
    budgets: { maxIterations: 3 },
    steps: [
      { id: "select_tasks", type: "context.load" },
      { id: "extract_lessons", type: "agent.review", promptModule: "context.harvest.extract" },
      { id: "write_proposals", type: "context.propose" },
      { id: "verify_context", type: "check.run", command: "agentplane context check" },
      { id: "evaluator", type: "evaluator.run", evaluator: "context-quality" },
    ],
    transitions: [
      {
        from: "evaluator",
        if: "verify_context.ok && evaluator.verdict == 'pass'",
        to: "human_review",
        decision: "request_human_review",
      },
      { from: "evaluator", if: "no_reusable_knowledge", to: "finish", decision: "finish_noop" },
    ],
    outputs: { required: COMMON_OUTPUTS },
    stopConditions: [
      { id: "no_reusable_knowledge", reason: "No reusable lesson found.", decision: "finish_noop" },
    ],
  },
  {
    schemaVersion: 1,
    id: "workflow.recover",
    version: "0.1.0",
    title: "Workflow recovery loop",
    description: "Recover deterministic task, branch, worktree, or PR lifecycle drift.",
    kind: "recovery",
    status: "experimental",
    appliesTo: {
      taskKinds: ["ops", "code"],
      taskTags: ["workflow", "recover"],
      workflowModes: ["direct", "branch_pr"],
    },
    permissions: {
      canModifyTaskArtifacts: true,
      canModifyCode: false,
      canModifyGitHistory: false,
      canDeleteBranches: "approval_required",
    },
    budgets: { maxIterations: 4 },
    steps: [
      { id: "route_status", type: "task.route_status" },
      { id: "next_action", type: "task.next_action" },
      { id: "classify_safety", type: "policy.check" },
      { id: "apply_safe_action", type: "command.run", when: "classify_safety.safe" },
      { id: "recheck", type: "task.route_status" },
    ],
    transitions: [
      { from: "recheck", if: "recheck.clean", to: "finish", decision: "finish" },
      {
        from: "classify_safety",
        if: "classify_safety.requires_human",
        to: "human_review",
        decision: "request_human_review",
      },
    ],
    outputs: { required: COMMON_OUTPUTS },
    stopConditions: [
      {
        id: "unsafe_mutation",
        reason: "Recovery action is not deterministic and safe.",
        decision: "request_human_review",
      },
    ],
  },
  {
    schemaVersion: 1,
    id: "evaluator.quality-gate",
    version: "0.1.0",
    title: "Evaluator quality gate loop",
    description: "Run evaluator feedback as a bounded pass/rework/block gate.",
    kind: "review",
    status: "experimental",
    appliesTo: {
      taskKinds: ["code", "docs", "release"],
      taskTags: ["quality", "evaluator"],
      workflowModes: ["direct", "branch_pr"],
    },
    permissions: { canEditFiles: false, canRunCommands: true },
    budgets: { maxIterations: 2 },
    steps: [
      { id: "load_evidence", type: "context.load" },
      { id: "evaluate", type: "evaluator.run", evaluator: "recovery-context" },
      { id: "decision", type: "decision.route" },
    ],
    transitions: [
      { from: "decision", if: "evaluator.verdict == 'pass'", to: "finish", decision: "finish" },
      {
        from: "decision",
        if: "evaluator.verdict == 'rework'",
        to: "human_review",
        decision: "request_human_review",
      },
    ],
    outputs: { required: COMMON_OUTPUTS },
    stopConditions: [
      {
        id: "unresolved_finding",
        reason: "Evaluator finding remains unresolved.",
        decision: "request_human_review",
      },
    ],
  },
  {
    schemaVersion: 1,
    id: "loop.improve",
    version: "0.1.0",
    title: "Loop improvement proposal loop",
    description: "Analyze completed LoopRuns and propose a new loop version without activation.",
    kind: "meta",
    status: "experimental",
    appliesTo: {
      taskKinds: ["analysis"],
      taskTags: ["agentplane", "loop", "evaluation"],
      workflowModes: ["direct", "branch_pr"],
    },
    permissions: {
      canEditFiles: true,
      canModifyLoops: "propose_only",
      canActivateLoops: false,
      canModifyPolicy: false,
    },
    budgets: { maxIterations: 2 },
    steps: [
      { id: "aggregate", type: "metrics.aggregate" },
      { id: "classify_failures", type: "agent.review", promptModule: "loop.failure-classifier" },
      { id: "propose_candidate", type: "agent.run", promptModule: "loop.improvement-proposal" },
      { id: "compare", type: "metrics.compare" },
      { id: "write_proposal", type: "artifact.write" },
    ],
    transitions: [
      {
        from: "compare",
        if: "compare.candidate_better && no_policy_regression",
        to: "write_proposal",
        decision: "request_human_review",
      },
      { from: "compare", if: "compare.regression_detected", to: "finish", decision: "reject" },
    ],
    outputs: { required: COMMON_OUTPUTS },
    stopConditions: [
      {
        id: "insufficient_evidence",
        reason: "No baseline scenarios or comparable LoopRuns.",
        decision: "block",
      },
    ],
  },
] as const satisfies readonly LoopSpec[];
