core:
  - "packages/**"
  - "schemas/**"
  - "scripts/**"
  - "!scripts/generate-website-docs.mjs"
  - "!scripts/check-design-language.mjs"
  - ".agentplane/**"
  - "package.json"
  - "bun.lock"
  - "tsconfig*.json"
  - "eslint.config.cjs"
  - "vitest.config.ts"
  - ".github/workflows/**"
  - ".github/path-filters.yml"
