import { describe, expect, it } from "vitest";
import * as recipes from "@agentplaneorg/recipes";

import {
  AGENTPLANE_HOME_ENV,
  DEFAULT_RECIPES_INDEX_URL,
  GLOBAL_RECIPES_DIR_NAME,
  INSTALLED_RECIPES_NAME,
  PROJECT_RECIPES_CACHE_DIR_NAME,
  PROJECT_RECIPES_PACKAGES_DIR_NAME,
  PROJECT_RECIPES_REGISTRY_NAME,
  RECIPES_DIR_NAME,
  RECIPES_INDEX_PUBLIC_KEYS,
  RECIPES_INDEX_PUBLIC_KEYS_ENV,
  RECIPES_REMOTE_INDEX_NAME,
  RECIPES_REMOTE_INDEX_SIG_NAME,
  RECIPES_SCENARIOS_DIR_NAME,
  RECIPES_SCENARIOS_INDEX_NAME,
} from "./constants.js";

describe("recipe command constants", () => {
  it("stays aligned with the recipes package contract", () => {
    expect({
      AGENTPLANE_HOME_ENV,
      DEFAULT_RECIPES_INDEX_URL,
      GLOBAL_RECIPES_DIR_NAME,
      INSTALLED_RECIPES_NAME,
      PROJECT_RECIPES_CACHE_DIR_NAME,
      PROJECT_RECIPES_PACKAGES_DIR_NAME,
      PROJECT_RECIPES_REGISTRY_NAME,
      RECIPES_DIR_NAME,
      RECIPES_INDEX_PUBLIC_KEYS,
      RECIPES_INDEX_PUBLIC_KEYS_ENV,
      RECIPES_REMOTE_INDEX_NAME,
      RECIPES_REMOTE_INDEX_SIG_NAME,
      RECIPES_SCENARIOS_DIR_NAME,
      RECIPES_SCENARIOS_INDEX_NAME,
    }).toEqual({
      AGENTPLANE_HOME_ENV: recipes.AGENTPLANE_HOME_ENV,
      DEFAULT_RECIPES_INDEX_URL: recipes.DEFAULT_RECIPES_INDEX_URL,
      GLOBAL_RECIPES_DIR_NAME: recipes.GLOBAL_RECIPES_DIR_NAME,
      INSTALLED_RECIPES_NAME: recipes.INSTALLED_RECIPES_NAME,
      PROJECT_RECIPES_CACHE_DIR_NAME: recipes.PROJECT_RECIPES_CACHE_DIR_NAME,
      PROJECT_RECIPES_PACKAGES_DIR_NAME: recipes.PROJECT_RECIPES_PACKAGES_DIR_NAME,
      PROJECT_RECIPES_REGISTRY_NAME: recipes.PROJECT_RECIPES_REGISTRY_NAME,
      RECIPES_DIR_NAME: recipes.RECIPES_DIR_NAME,
      RECIPES_INDEX_PUBLIC_KEYS: recipes.RECIPES_INDEX_PUBLIC_KEYS,
      RECIPES_INDEX_PUBLIC_KEYS_ENV: recipes.RECIPES_INDEX_PUBLIC_KEYS_ENV,
      RECIPES_REMOTE_INDEX_NAME: recipes.RECIPES_REMOTE_INDEX_NAME,
      RECIPES_REMOTE_INDEX_SIG_NAME: recipes.RECIPES_REMOTE_INDEX_SIG_NAME,
      RECIPES_SCENARIOS_DIR_NAME: recipes.RECIPES_SCENARIOS_DIR_NAME,
      RECIPES_SCENARIOS_INDEX_NAME: recipes.RECIPES_SCENARIOS_INDEX_NAME,
    });
  });
});
