import { mkdir, readFile } from "node:fs/promises";
import path from "node:path";

import { resolveProject } from "@agentplaneorg/core";

import { mapCoreError } from "../../error-map.js";
import { writeTextIfChanged } from "../../../shared/write-if-changed.js";
import type { CommandHandler, CommandSpec } from "../../../cli2/spec.js";

type IdeSyncParsed = { ide?: "cursor" | "windsurf" };

export const ideSyncSpec: CommandSpec<IdeSyncParsed> = {
  id: ["ide", "sync"],
  group: "IDE",
  summary: "Generate IDE entrypoints from AGENTS.md.",
  options: [
    {
      kind: "string",
      name: "ide",
      valueHint: "<cursor|windsurf>",
      choices: ["cursor", "windsurf"],
      description: "Only generate rules for a single IDE (default: both).",
    },
  ],
  examples: [
    { cmd: "agentplane ide sync", why: "Generate Cursor + Windsurf rules." },
    { cmd: "agentplane ide sync --ide cursor", why: "Generate Cursor rules only." },
  ],
  parse: (raw) => ({ ide: raw.opts.ide as IdeSyncParsed["ide"] }),
};

export async function cmdIdeSync(opts: {
  cwd: string;
  rootOverride?: string;
  ide?: "cursor" | "windsurf";
}): Promise<number> {
  try {
    const resolved = await resolveProject({
      cwd: opts.cwd,
      rootOverride: opts.rootOverride ?? null,
    });
    const agentsPath = path.join(resolved.gitRoot, "AGENTS.md");
    const agentsText = await readFile(agentsPath, "utf8");

    const header = [
      "<!--",
      "  AUTOGENERATED by agentplane ide sync.",
      "  DO NOT EDIT MANUALLY.",
      "  Source: AGENTS.md",
      "-->",
      "",
    ].join("\n");
    const content = `${header}${agentsText.trimEnd()}\n`;

    const targets =
      opts.ide === "cursor"
        ? ["cursor"]
        : opts.ide === "windsurf"
          ? ["windsurf"]
          : ["cursor", "windsurf"];

    if (targets.includes("cursor")) {
      const cursorDir = path.join(resolved.gitRoot, ".cursor", "rules");
      await mkdir(cursorDir, { recursive: true });
      const cursorPath = path.join(cursorDir, "agentplane.mdc");
      await writeTextIfChanged(cursorPath, content);
      process.stdout.write(`${path.relative(resolved.gitRoot, cursorPath)}\n`);
    }

    if (targets.includes("windsurf")) {
      const windsurfDir = path.join(resolved.gitRoot, ".windsurf", "rules");
      await mkdir(windsurfDir, { recursive: true });
      const windsurfPath = path.join(windsurfDir, "agentplane.md");
      await writeTextIfChanged(windsurfPath, content);
      process.stdout.write(`${path.relative(resolved.gitRoot, windsurfPath)}\n`);
    }
    return 0;
  } catch (err) {
    throw mapCoreError(err, { command: "ide sync", root: opts.rootOverride ?? null });
  }
}

export const runIdeSync: CommandHandler<IdeSyncParsed> = (ctx, p) =>
  cmdIdeSync({ cwd: ctx.cwd, rootOverride: ctx.rootOverride, ide: p.ide });
