import { mkdir, readdir, readFile } from "node:fs/promises";
import path from "node:path";

import { writeTextIfChanged } from "../../../shared/write-if-changed.js";
import { resolvePolicyGatewayForRepo } from "../../../shared/policy-gateway.js";
import { renderRole, type RoleProfileGuide } from "../../command-guide.js";
import type { CommandHandler, CommandSpec } from "../../spec/spec.js";
import type { RunDeps } from "../command-catalog.js";
import { wrapCommand } from "./wrap-command.js";

type IdeSyncParsed = { ide?: "cursor" | "windsurf" };

export const ideSyncSpec: CommandSpec<IdeSyncParsed> = {
  id: ["ide", "sync"],
  group: "IDE",
  summary: "Generate IDE entrypoints from policy gateway file (AGENTS.md or CLAUDE.md).",
  options: [
    {
      kind: "string",
      name: "ide",
      valueHint: "<cursor|windsurf>",
      choices: ["cursor", "windsurf"],
      description: "Only generate rules for a single IDE (default: both).",
    },
  ],
  examples: [
    { cmd: "agentplane ide sync", why: "Generate Cursor + Windsurf rules." },
    { cmd: "agentplane ide sync --ide cursor", why: "Generate Cursor rules only." },
  ],
  parse: (raw) => ({ ide: raw.opts.ide as IdeSyncParsed["ide"] }),
};

export async function cmdIdeSync(opts: {
  cwd: string;
  rootOverride?: string;
  ide?: "cursor" | "windsurf";
  deps: RunDeps;
}): Promise<number> {
  return wrapCommand({ command: "ide sync", rootOverride: opts.rootOverride }, async () => {
    const resolved = await opts.deps.getResolvedProject("ide sync");
    const gateway = await resolvePolicyGatewayForRepo({
      gitRoot: resolved.gitRoot,
      fallbackFlavor: "codex",
    });
    const agentsPath = gateway.absPath;
    const agentsText = await readFile(agentsPath, "utf8");
    const roleGuides = await loadInstalledRoleGuides(resolved.agentplaneDir);

    const header = [
      "<!--",
      "  AUTOGENERATED by agentplane ide sync.",
      "  DO NOT EDIT MANUALLY.",
      `  Source: ${gateway.fileName}`,
      "-->",
      "",
    ].join("\n");
    const roleGuideText =
      roleGuides.length === 0
        ? ""
        : [
            "",
            "## Synced Role Activation",
            "",
            "- Use `agentplane role ORCHESTRATOR` while planning and approvals are active.",
            "- As soon as a task owner is known, switch to that owner role before owner-scoped execution.",
            "- Do not keep implementation or verification inside ORCHESTRATOR once the task owner is established.",
            "",
            ...roleGuides,
          ].join("\n");
    const content = `${header}${agentsText.trimEnd()}${roleGuideText}\n`;

    const targets =
      opts.ide === "cursor"
        ? ["cursor"]
        : opts.ide === "windsurf"
          ? ["windsurf"]
          : ["cursor", "windsurf"];

    if (targets.includes("cursor")) {
      const cursorDir = path.join(resolved.gitRoot, ".cursor", "rules");
      await mkdir(cursorDir, { recursive: true });
      const cursorPath = path.join(cursorDir, "agentplane.mdc");
      await writeTextIfChanged(cursorPath, content);
      process.stdout.write(`${path.relative(resolved.gitRoot, cursorPath)}\n`);
    }

    if (targets.includes("windsurf")) {
      const windsurfDir = path.join(resolved.gitRoot, ".windsurf", "rules");
      await mkdir(windsurfDir, { recursive: true });
      const windsurfPath = path.join(windsurfDir, "agentplane.md");
      await writeTextIfChanged(windsurfPath, content);
      process.stdout.write(`${path.relative(resolved.gitRoot, windsurfPath)}\n`);
    }
    return 0;
  });
}

export function makeRunIdeSyncHandler(deps: RunDeps): CommandHandler<IdeSyncParsed> {
  return (ctx, p) => cmdIdeSync({ cwd: ctx.cwd, rootOverride: ctx.rootOverride, ide: p.ide, deps });
}

type IdeAgentProfile = {
  id?: string;
  role?: string;
  description?: string;
  inputs?: unknown;
  outputs?: unknown;
  permissions?: unknown;
  workflow?: unknown;
};

function toStringList(value: unknown): string[] {
  return Array.isArray(value)
    ? value
        .filter((item): item is string => typeof item === "string")
        .map((item) => item.trim())
        .filter(Boolean)
    : [];
}

function toRoleProfileGuide(opts: {
  filename: string;
  roleId: string;
  profile: IdeAgentProfile;
}): RoleProfileGuide {
  return {
    filename: opts.filename,
    id: (typeof opts.profile.id === "string" ? opts.profile.id : "").trim() || opts.roleId,
    role: (typeof opts.profile.role === "string" ? opts.profile.role : "").trim(),
    description: (typeof opts.profile.description === "string"
      ? opts.profile.description
      : ""
    ).trim(),
    inputs: toStringList(opts.profile.inputs),
    outputs: toStringList(opts.profile.outputs),
    permissions: toStringList(opts.profile.permissions),
    workflow: toStringList(opts.profile.workflow),
  };
}

async function loadInstalledRoleGuides(agentplaneDir: string): Promise<string[]> {
  const agentsDir = path.join(agentplaneDir, "agents");
  let entries: string[] = [];
  try {
    const dirEntries = await readdir(agentsDir);
    entries = dirEntries.filter((entry) => entry.endsWith(".json")).toSorted();
  } catch {
    return [];
  }

  const guides: string[] = [];
  for (const entry of entries) {
    const roleId = entry.replace(/\.json$/i, "");
    const raw = JSON.parse(await readFile(path.join(agentsDir, entry), "utf8")) as IdeAgentProfile;
    const guide = renderRole(roleId, {
      profile: toRoleProfileGuide({
        filename: entry,
        roleId,
        profile: raw,
      }),
    });
    if (guide) guides.push(guide);
  }
  return guides;
}
