export const PLATFORM_IDS = [
  "codex",
  "claude",
  "gemini",
  "opencode",
  "copilot",
  "cursor",
  "windsurf",
  "cline",
  "kiro",
  "openclaw",
  "hermes",
] as const;

export type PlatformId = (typeof PLATFORM_IDS)[number];

export type PlatformSurfaceKind = "native" | "generated" | "external";

export type PlatformRenderContext = {
  command: string;
  sourceFileName: string;
  sourceText: string;
  roleGuideText: string;
};

type PlatformProjection = {
  path: string;
  description: string;
  render: (ctx: PlatformRenderContext) => string;
};

export type PlatformIntegration = {
  id: PlatformId;
  label: string;
  summary: string;
  surfaces: PlatformSurfaceKind[];
  nativeSources: string[];
  projections: PlatformProjection[];
  externalAdapter?: {
    repository: string;
    note: string;
  };
  doctorHint: string;
};

function projectionHeader(opts: { command: string; sourceFileName: string }): string {
  return [
    "<!--",
    `  AUTOGENERATED by agentplane ${opts.command}.`,
    "  DO NOT EDIT MANUALLY.",
    `  Source: ${opts.sourceFileName}`,
    "-->",
    "",
  ].join("\n");
}

function renderFullProjection(ctx: PlatformRenderContext): string {
  return `${projectionHeader({ command: ctx.command, sourceFileName: ctx.sourceFileName })}${ctx.sourceText.trimEnd()}${ctx.roleGuideText}\n`;
}

function renderCompactProjection(ctx: PlatformRenderContext): string {
  return [
    projectionHeader({ command: ctx.command, sourceFileName: ctx.sourceFileName }).trimEnd(),
    "",
    "# AgentPlane Discipline",
    "",
    `Read and follow \`${ctx.sourceFileName}\` as the repository policy gateway.`,
    "",
    "- Use `agentplane quickstart` before starting work.",
    "- Use `agentplane task brief <task-id>` before owner-scoped execution.",
    "- Use `agentplane task next-action <task-id> --explain` as the route oracle in branch_pr repositories.",
    "- Use AgentPlane CLI commands for task lifecycle, verification, and finish evidence.",
    "- Do not edit `.agentplane/tasks.json` or generated task state manually.",
    "- Record verification before asking for review.",
    "",
  ].join("\n");
}

export const PLATFORM_INTEGRATIONS: Record<PlatformId, PlatformIntegration> = {
  codex: {
    id: "codex",
    label: "Codex",
    summary: "Native AGENTS.md plus optional AgentPlane Codex plugin/skill.",
    surfaces: ["native"],
    nativeSources: ["AGENTS.md"],
    projections: [],
    doctorHint: "Codex should list AGENTS.md in its instruction chain for this repository.",
  },
  claude: {
    id: "claude",
    label: "Claude Code",
    summary: "CLAUDE.md project memory projection for Claude Code.",
    surfaces: ["generated"],
    nativeSources: ["CLAUDE.md"],
    projections: [
      {
        path: "CLAUDE.md",
        description: "Claude Code project memory",
        render: (ctx) => renderFullProjection(ctx),
      },
    ],
    doctorHint: "Run `/memory` in Claude Code and confirm CLAUDE.md is loaded.",
  },
  gemini: {
    id: "gemini",
    label: "Gemini CLI",
    summary: "GEMINI.md context projection for Gemini CLI.",
    surfaces: ["generated"],
    nativeSources: ["GEMINI.md"],
    projections: [
      {
        path: "GEMINI.md",
        description: "Gemini CLI context file",
        render: (ctx) => renderFullProjection(ctx),
      },
    ],
    doctorHint: "Start Gemini CLI in the repository and confirm GEMINI.md appears in context.",
  },
  opencode: {
    id: "opencode",
    label: "OpenCode",
    summary: "Native AGENTS.md discipline; optional opencode.json instructions can point to it.",
    surfaces: ["native"],
    nativeSources: ["AGENTS.md", "CLAUDE.md"],
    projections: [],
    doctorHint: "OpenCode should discover AGENTS.md from the project root before global rules.",
  },
  copilot: {
    id: "copilot",
    label: "GitHub Copilot",
    summary: "Repository custom instructions for Copilot Chat, cloud agent, and code review.",
    surfaces: ["generated"],
    nativeSources: [".github/copilot-instructions.md"],
    projections: [
      {
        path: ".github/copilot-instructions.md",
        description: "GitHub Copilot repository custom instructions",
        render: (ctx) => renderCompactProjection(ctx),
      },
      {
        path: ".github/instructions/agentplane-state.instructions.md",
        description: "Path-specific Copilot instructions for AgentPlane state",
        render: (ctx) =>
          [
            "---",
            'applyTo: ".agentplane/**"',
            "---",
            "",
            renderCompactProjection(ctx).trimEnd(),
            "",
            "For files under `.agentplane/**`, use AgentPlane CLI commands instead of hand-editing task state.",
            "",
          ].join("\n"),
      },
    ],
    doctorHint: "Open Copilot Chat references and confirm copilot-instructions.md is attached.",
  },
  cursor: {
    id: "cursor",
    label: "Cursor",
    summary: "Cursor project rule projection.",
    surfaces: ["generated"],
    nativeSources: ["AGENTS.md", ".cursor/rules/*"],
    projections: [
      {
        path: ".cursor/rules/agentplane.mdc",
        description: "Cursor project rule",
        render: (ctx) => renderFullProjection(ctx),
      },
    ],
    doctorHint: "Open Cursor Settings > Rules and confirm the AgentPlane project rule is visible.",
  },
  windsurf: {
    id: "windsurf",
    label: "Windsurf Cascade",
    summary: "Windsurf/Cascade workspace rule projection with legacy compatibility file.",
    surfaces: ["generated"],
    nativeSources: ["AGENTS.md", ".devin/rules/*", ".windsurf/rules/*"],
    projections: [
      {
        path: ".devin/rules/agentplane.md",
        description: "Cascade workspace rule",
        render: (ctx) => renderFullProjection(ctx),
      },
      {
        path: ".windsurf/rules/agentplane.md",
        description: "Legacy Windsurf workspace rule",
        render: (ctx) => renderFullProjection(ctx),
      },
    ],
    doctorHint:
      "Open Cascade Customizations > Rules and confirm the AgentPlane workspace rule is enabled.",
  },
  cline: {
    id: "cline",
    label: "Cline",
    summary: "Cline workspace rules projection.",
    surfaces: ["generated"],
    nativeSources: ["AGENTS.md", ".clinerules/*"],
    projections: [
      {
        path: ".clinerules/00-agentplane.md",
        description: "Cline workspace rule",
        render: (ctx) => renderFullProjection(ctx),
      },
    ],
    doctorHint: "Open Cline Rules panel and confirm 00-agentplane.md is enabled.",
  },
  kiro: {
    id: "kiro",
    label: "Kiro",
    summary: "Kiro workspace steering projection.",
    surfaces: ["generated"],
    nativeSources: ["AGENTS.md", ".kiro/steering/*"],
    projections: [
      {
        path: ".kiro/steering/agentplane.md",
        description: "Kiro workspace steering file",
        render: (ctx) => renderFullProjection(ctx),
      },
    ],
    doctorHint: "Open Kiro Steering and confirm agentplane.md is loaded for the workspace.",
  },
  openclaw: {
    id: "openclaw",
    label: "OpenClaw",
    summary:
      "Native per-agent workspace AGENTS.md; external AgentPlane OpenClaw plugin owns deeper integration.",
    surfaces: ["native", "external"],
    nativeSources: ["AGENTS.md", "SOUL.md", "USER.md"],
    projections: [],
    externalAdapter: {
      repository: "https://github.com/basilisk-labs/agentplane-openclaw-plugin",
      note: "Install the OpenClaw plugin for platform-native lifecycle integration; keep AgentPlane discipline in each agent workspace AGENTS.md.",
    },
    doctorHint:
      "Verify the target OpenClaw agent workspace contains AGENTS.md and the plugin is installed when lifecycle integration is needed.",
  },
  hermes: {
    id: "hermes",
    label: "Hermes",
    summary: "External AgentPlane Hermes plugin plus repository AGENTS.md discipline.",
    surfaces: ["native", "external"],
    nativeSources: ["AGENTS.md"],
    projections: [],
    externalAdapter: {
      repository: "https://github.com/basilisk-labs/agentplane-hermes-plugin",
      note: "Install the Hermes plugin for worker-lane integration; keep AgentPlane task truth in the repository.",
    },
    doctorHint:
      "Verify the Hermes plugin is installed and repository AGENTS.md is visible to spawned workers.",
  },
};
