export function renderHelp(): string {
  return [
    "agentplane (v1 prototype)",
    "",
    "Usage:",
    "  agentplane [--root <path>] [--json] <namespace> <command> [options]",
    "  agentplane [--root <path>] [--json] <command> [options]",
    "",
    "Core namespaces (implemented in this prototype): config, mode, task",
    "Core namespaces (planned): ide, backend, recipe",
    "",
    "Flags:",
    "  --help, -h     Show help",
    "  --version      Show version",
    "  --root <path>  Treat <path> as project root",
    "",
    "Config commands:",
    "  agentplane config show",
    "  agentplane config set <key> <value>",
    "",
    "Mode commands:",
    "  agentplane mode get",
    "  agentplane mode set <direct|branch_pr>",
    "",
    "Branch commands:",
    "  agentplane branch base get",
    "  agentplane branch base set <name>",
    "",
    "Work commands:",
    "  agentplane work start <task-id> --agent <id> --slug <slug> --worktree",
    "",
    "Guard commands:",
    "  agentplane guard clean",
    "  agentplane guard suggest-allow [--format lines|args]",
    "  agentplane guard commit <task-id> -m <message> --allow <path> [--allow <path>...]",
    "",
    "Commit commands:",
    "  agentplane commit <task-id> -m <message> --allow <path> [--allow <path>...]",
    "  agentplane commit <task-id> -m <message> --auto-allow",
    "",
    "Hooks commands:",
    "  agentplane hooks install [--quiet]",
    "  agentplane hooks uninstall [--quiet]",
    "",
    "Task commands:",
    "  agentplane task list",
    "  agentplane task show <task-id>",
    "  agentplane task new --title <text> --description <text> --priority <low|normal|med|high> --owner <id> --tag <tag> [--tag <tag>...]",
    "  agentplane task doc set <task-id> --section <name> (--text <text> | --file <path>)",
    "  agentplane task export",
    "  agentplane task lint",
    "",
    "Start commands:",
    "  agentplane start <task-id> --author <id> --body <text> [--commit-from-comment]",
    "",
    "Block commands:",
    "  agentplane block <task-id> --author <id> --body <text>",
    "",
    "Finish commands:",
    "  agentplane finish <task-id> --author <id> --body <text>",
    "",
  ].join("\n");
}
