export function renderHelp(): string {
  return [
    "agentplane (v1 prototype)",
    "",
    "Usage:",
    "  agentplane [--root <path>] [--json] <namespace> <command> [options]",
    "  agentplane [--root <path>] [--json] <command> [options]",
    "",
    "Core namespaces (implemented in this prototype): config, mode, task",
    "Core namespaces (planned): ide, backend, recipe",
    "",
    "Flags:",
    "  --help, -h     Show help",
    "  --version      Show version",
    "  --root <path>  Treat <path> as project root",
    "",
    "Config commands:",
    "  agentplane config show",
    "  agentplane config set <key> <value>",
    "",
    "Mode commands:",
    "  agentplane mode get",
    "  agentplane mode set <direct|branch_pr>",
    "",
    "Task commands:",
    "  agentplane task list",
    "  agentplane task show <task-id>",
    "  agentplane task new --title <text> --description <text> --priority <low|normal|med|high> --owner <id> --tag <tag> [--tag <tag>...]",
    "  agentplane task doc set <task-id> --section <name> (--text <text> | --file <path>)",
    "  agentplane task export",
    "  agentplane task lint",
    "",
  ].join("\n");
}
