import { usageError } from "../../cli/spec/errors.js";
import type { CommandSpec } from "../../cli/spec/spec.js";
import type { ReleaseApplyParsed } from "./apply.types.js";

export const releaseApplySpec: CommandSpec<ReleaseApplyParsed> = {
  id: ["release", "apply"],
  group: "Release",
  summary: "Apply a prepared direct-mode release: bump versions, validate notes, commit, and tag.",
  description:
    "Applies a release plan generated by `agentplane release plan` on the direct release route. This command does not author release notes; it expects a DOCS agent to have written docs/releases/vX.Y.Z.md. In branch_pr repositories, use `agentplane release candidate` on a dedicated non-base branch instead.",
  options: [
    {
      kind: "string",
      name: "plan",
      valueHint: "<path>",
      description:
        "Path to a release plan directory (defaults to the latest under .agentplane/.release/plan/).",
    },
    {
      kind: "boolean",
      name: "push",
      default: false,
      description:
        "Optional direct-push mode: push the release commit and tag immediately " +
        "(requires --yes). This is for the direct release route only.",
    },
    {
      kind: "string",
      name: "remote",
      valueHint: "<name>",
      description: "Git remote to push to (default: origin).",
    },
    {
      kind: "boolean",
      name: "yes",
      default: false,
      description:
        "Approve minor/major bumps and allow pushing. Patch bumps can be applied without this flag.",
    },
  ],
  parse: (raw) => {
    return {
      plan: raw.opts.plan as string | undefined,
      push: raw.opts.push === true,
      remote: (raw.opts.remote as string | undefined) ?? "origin",
      yes: raw.opts.yes === true,
    };
  },
  validate: (p) => {
    if (p.push && p.yes !== true) {
      throw usageError({
        spec: releaseApplySpec,
        command: "release apply",
        message: "Option --push requires explicit approval. Re-run with --yes.",
      });
    }
    if (!p.remote.trim()) {
      throw usageError({
        spec: releaseApplySpec,
        command: "release apply",
        message: "Option --remote must be non-empty.",
      });
    }
  },
  examples: [
    {
      cmd: "agentplane release apply",
      why: "Apply the latest release plan locally (expects docs/releases/vX.Y.Z.md to exist).",
    },
    {
      cmd: "agentplane release apply --plan .agentplane/.release/plan/<runId>",
      why: "Apply a specific release plan directory.",
    },
    {
      cmd: "agentplane release apply --push --yes",
      why: "Apply and push the release commit+tag to the remote.",
    },
  ],
};

const releaseCandidateOptions: CommandSpec<ReleaseApplyParsed>["options"] = [
  {
    kind: "string",
    name: "plan",
    valueHint: "<path>",
    description:
      "Path to a release plan directory (defaults to the latest under .agentplane/.release/plan/).",
  },
  {
    kind: "boolean",
    name: "push",
    default: false,
    description:
      "Optional candidate-push mode: push only the release candidate branch for hosted review and merge (requires --yes). The release tag is not created or pushed here.",
  },
  {
    kind: "string",
    name: "remote",
    valueHint: "<name>",
    description: "Git remote to push to (default: origin).",
  },
  {
    kind: "boolean",
    name: "yes",
    default: false,
    description:
      "Approve minor/major bumps and allow pushing. Patch bumps can be applied without this flag.",
  },
];

export const releaseCandidateSpec: CommandSpec<ReleaseApplyParsed> = {
  id: ["release", "candidate"],
  group: "Release",
  summary:
    "Prepare a branch_pr release candidate: bump versions, validate notes, commit, and optionally push the candidate branch.",
  description:
    "Prepares a release candidate from a generated release plan on a dedicated non-base branch in branch_pr mode. This command creates the candidate commit but intentionally does not create or push the release tag; final publication remains gated on merge to the protected base branch and explicit Publish to npm workflow dispatch with the release commit sha.",
  options: releaseCandidateOptions,
  parse: releaseApplySpec.parse,
  validate: (p) => {
    if (p.push && p.yes !== true) {
      throw usageError({
        spec: releaseCandidateSpec,
        command: "release candidate",
        message: "Option --push requires explicit approval. Re-run with --yes.",
      });
    }
    if (!p.remote.trim()) {
      throw usageError({
        spec: releaseCandidateSpec,
        command: "release candidate",
        message: "Option --remote must be non-empty.",
      });
    }
  },
  examples: [
    {
      cmd: "agentplane release candidate",
      why: "Prepare the latest release plan on the current branch_pr candidate branch.",
    },
    {
      cmd: "agentplane release candidate --plan .agentplane/.release/plan/<runId>",
      why: "Prepare a specific release plan on the current candidate branch.",
    },
    {
      cmd: "agentplane release candidate --push --yes",
      why: "Prepare and push only the release candidate branch for hosted review and merge.",
    },
  ],
};
