import type { CommandSpec } from "../../cli/spec/spec.js";

import type { TaskNewParsed } from "./new.js";
import { normalizeDependsOnInput } from "./shared.js";

export const taskNewSpec: CommandSpec<TaskNewParsed> = {
  id: ["task", "new"],
  group: "Task",
  summary: "Create a new task (prints the generated task id).",
  description:
    "Creates a TODO task with doc_version=3, seeds the README v3 section layout, and writes it via the configured task backend.",
  options: [
    {
      kind: "string",
      name: "title",
      valueHint: "<text>",
      required: true,
      description: "Task title.",
    },
    {
      kind: "string",
      name: "description",
      valueHint: "<text>",
      required: true,
      description: "Task description.",
    },
    {
      kind: "string",
      name: "owner",
      valueHint: "<id>",
      required: true,
      description: "Owner id (e.g. CODER).",
    },
    {
      kind: "string",
      name: "priority",
      valueHint: "<low|normal|med|high>",
      choices: ["low", "normal", "med", "high"],
      default: "med",
      description: "Task priority (default: med).",
    },
    {
      kind: "string",
      name: "tag",
      valueHint: "<tag>",
      repeatable: true,
      minCount: 1,
      description: "Repeatable. Adds a tag (must provide at least one).",
    },
    {
      kind: "string",
      name: "task-kind",
      valueHint: "<analysis|content|docs|code|release|ops|context>",
      choices: ["analysis", "content", "docs", "code", "release", "ops", "context"],
      description: "Structured blueprint task-kind intent. Tags/title remain fallback hints.",
    },
    {
      kind: "string",
      name: "mutation-scope",
      valueHint: "<none|docs|code|release|ops|context|unknown>",
      choices: ["none", "docs", "code", "release", "ops", "context", "unknown"],
      description: "Structured mutation scope used by blueprint resolution.",
    },
    {
      kind: "string",
      name: "risk",
      valueHint: "<risk>",
      repeatable: true,
      choices: [
        "network",
        "credentials",
        "deploy",
        "publish",
        "merge",
        "security",
        "external_system",
      ],
      description: "Structured risk flag used by blueprint resolution. Repeatable.",
    },
    {
      kind: "string",
      name: "blueprint-request",
      valueHint: "<id>",
      choices: [
        "analysis.light",
        "content.light",
        "docs.change",
        "code.direct",
        "code.branch_pr",
        "performance.benchmark",
        "quality.regression",
        "context.assimilation",
        "context.maximum_assimilation",
        "post_run.improvement_review",
        "release.strict",
        "ops.approval",
      ],
      description: "Explicit blueprint request stored on the task; resolver still validates it.",
    },
    {
      kind: "string",
      name: "depends-on",
      valueHint: "<task-id>",
      repeatable: true,
      coerce: (raw) => normalizeDependsOnInput(raw),
      description: "Repeatable. Adds a dependency. Special-case: '[]' is treated as empty.",
    },
    {
      kind: "string",
      name: "verify",
      valueHint: "<command>",
      repeatable: true,
      description: "Repeatable. Verification commands/checks to run for this task.",
    },
    {
      kind: "boolean",
      name: "show-blueprint",
      default: false,
      description:
        "Print a resolved blueprint route preview to stderr after creation without changing stdout.",
    },
    {
      kind: "boolean",
      name: "allow-duplicate",
      default: false,
      description:
        "Allow creating a task even when an open task with a highly similar title already exists.",
    },
  ],
  examples: [
    {
      cmd: 'agentplane task new --title "Refactor CLI" --description "Improve CLI output" --owner CODER --tag cli',
      why: "Create a new task with one tag.",
    },
    {
      cmd: 'agentplane task new --title "Market analysis note" --description "Analyze market context" --owner ANALYST --tag analysis --task-kind analysis --mutation-scope none --show-blueprint',
      why: "Create a task and preview the resolved route without changing the task-id stdout contract.",
    },
  ],
  notes: [
    "Task creation defaults to doc_version=3 and seeds the README v3 section contract automatically.",
    "For verify-required primary tags, this command seeds a default ## Verify Steps acceptance contract in README.",
    "`--show-blueprint` writes route preview details to stderr; stdout remains only the generated task id.",
  ],
  parse: (raw) => ({
    title: raw.opts.title as string,
    description: raw.opts.description as string,
    owner: raw.opts.owner as string,
    priority: (raw.opts.priority ?? "med") as TaskNewParsed["priority"],
    tags: (raw.opts.tag ?? []) as string[],
    taskKind: raw.opts["task-kind"] as TaskNewParsed["taskKind"],
    mutationScope: raw.opts["mutation-scope"] as TaskNewParsed["mutationScope"],
    riskFlags: (raw.opts.risk ?? []) as TaskNewParsed["riskFlags"],
    blueprintRequest: raw.opts["blueprint-request"] as TaskNewParsed["blueprintRequest"],
    dependsOn: (raw.opts["depends-on"] ?? []) as string[],
    verify: (raw.opts.verify ?? []) as string[],
    showBlueprint: raw.opts["show-blueprint"] === true,
    allowDuplicate: raw.opts["allow-duplicate"] === true,
  }),
};
