import { mkdir, readdir, readFile, rm, rmdir } from "node:fs/promises";
import type { Dirent } from "node:fs";
import path from "node:path";

import { atomicWriteFile } from "@agentplaneorg/core/fs";

import { mapBackendError } from "../../cli/error-map.js";
import { handleTaskListWarnings } from "./shared/listing.js";
import { loadCommandContext, type CommandContext } from "../shared/task-backend.js";
import { toTaskSummaries, type TaskSummary } from "../../backends/task-backend.js";

export type ObsidianProjectionFile = {
  path: string;
  content: string;
};

export type ObsidianProjectionResult = {
  files: ObsidianProjectionFile[];
  taskCount: number;
};

export type ObsidianCleanResult = {
  deleted: string[];
  preserved: string[];
};

const GENERATED_NOTE = "<!-- Generated by agentplane task obsidian. Do not edit by hand. -->";
const OBSIDIAN_GROUP_DIRS = ["by-status", "by-tag", "by-owner"] as const;
const OBSIDIAN_PROJECTION_DIR = ".agentplane/generated/obsidian";

const STATUS_ORDER = ["TODO", "READY", "DOING", "BLOCKED", "REVIEW", "DONE"];
type ObsidianFromDir = "." | "by-status" | "by-tag" | "by-owner";

function stringArray(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return value.map((item) => String(item ?? "").trim()).filter(Boolean);
}

function escapeTableCell(value: unknown): string {
  const text =
    typeof value === "string" || typeof value === "number" || typeof value === "boolean"
      ? String(value)
      : "";
  return text
    .replaceAll("|", String.raw`\|`)
    .replaceAll("\n", " ")
    .trim();
}

function safeGroupName(value: string, fallback: string): string {
  const trimmed = value.trim();
  if (!trimmed) return fallback;
  return (
    trimmed
      .toLowerCase()
      .replaceAll(/[^a-z0-9._-]+/gu, "-")
      .replaceAll(/^-+|-+$/gu, "")
      .slice(0, 80) || fallback
  );
}

function uniqueGroupPath(
  dir: string,
  displayName: string,
  used: Set<string>,
  fallback: string,
): string {
  const base = safeGroupName(displayName, fallback);
  let candidate = `${dir}/${base}.md`;
  let index = 2;
  while (used.has(candidate)) {
    candidate = `${dir}/${base}-${index}.md`;
    index += 1;
  }
  used.add(candidate);
  return candidate;
}

function taskReadmeLink(taskId: string, fromDir: ObsidianFromDir): string {
  const prefix = fromDir === "." ? "../../" : "../../../";
  return `${prefix}tasks/${taskId}/README.md`;
}

function taskLink(taskId: string, fromDir: ObsidianFromDir): string {
  return `[${taskId}](${taskReadmeLink(taskId, fromDir)})`;
}

function taskTitle(task: TaskSummary): string {
  return task.title.trim() || task.id;
}

function taskTags(task: TaskSummary): string[] {
  return stringArray(task.tags);
}

function taskDeps(task: TaskSummary): string[] {
  return stringArray(task.depends_on);
}

function taskRow(task: TaskSummary, fromDir: ObsidianFromDir): string {
  const tags = taskTags(task);
  const deps = taskDeps(task);
  return [
    taskLink(task.id, fromDir),
    escapeTableCell(taskTitle(task)),
    escapeTableCell(task.status),
    escapeTableCell(task.owner),
    escapeTableCell(tags.length > 0 ? tags.join(", ") : "-"),
    escapeTableCell(deps.length > 0 ? deps.map((id) => taskLink(id, fromDir)).join(", ") : "-"),
  ].join(" | ");
}

function renderTaskTable(tasks: TaskSummary[], fromDir: ObsidianFromDir): string[] {
  if (tasks.length === 0) return ["No tasks.", ""];
  return [
    "| Task | Title | Status | Owner | Tags | Dependencies |",
    "| --- | --- | --- | --- | --- | --- |",
    ...tasks.map((task) => `| ${taskRow(task, fromDir)} |`),
    "",
  ];
}

function sortTasks(tasks: readonly TaskSummary[]): TaskSummary[] {
  return tasks.toSorted((a, b) => a.id.localeCompare(b.id));
}

function groupBy(
  tasks: readonly TaskSummary[],
  keyFor: (task: TaskSummary) => string[],
): Map<string, TaskSummary[]> {
  const groups = new Map<string, TaskSummary[]>();
  for (const task of tasks) {
    for (const key of keyFor(task)) {
      const next = groups.get(key) ?? [];
      next.push(task);
      groups.set(key, next);
    }
  }
  return groups;
}

function orderedStatusKeys(keys: Iterable<string>): string[] {
  const all = [...keys];
  return all.toSorted((a, b) => {
    const ai = STATUS_ORDER.indexOf(a.toUpperCase());
    const bi = STATUS_ORDER.indexOf(b.toUpperCase());
    if (ai !== -1 || bi !== -1) return (ai === -1 ? 999 : ai) - (bi === -1 ? 999 : bi);
    return a.localeCompare(b);
  });
}

function renderIndex(
  tasks: readonly TaskSummary[],
  groupPaths: {
    statuses: Map<string, string>;
    tags: Map<string, string>;
    owners: Map<string, string>;
  },
): string {
  const lines = [
    GENERATED_NOTE,
    "",
    "# AgentPlane",
    "",
    "Open this directory as an Obsidian vault to browse the generated task projection.",
    "",
    "- [All tasks](tasks.md)",
    `- Tasks: ${tasks.length}`,
    "",
    "## Status",
    "",
    ...[...groupPaths.statuses.entries()].map(([status, file]) => `- [${status}](${file})`),
    "",
    "## Tags",
    "",
    ...[...groupPaths.tags.entries()].map(([tag, file]) => `- [${tag}](${file})`),
    "",
    "## Owners",
    "",
    ...[...groupPaths.owners.entries()].map(([owner, file]) => `- [${owner}](${file})`),
    "",
    "## Source Of Truth",
    "",
    "Task README files under `.agentplane/tasks/<task-id>/README.md` remain canonical. These navigation files are derived projection artifacts.",
    "",
  ];
  return `${lines.join("\n").trimEnd()}\n`;
}

function renderTaskList(tasks: readonly TaskSummary[]): string {
  const lines = [GENERATED_NOTE, "", "# Tasks", "", ...renderTaskTable(sortTasks(tasks), ".")];
  return `${lines.join("\n").trimEnd()}\n`;
}

function renderGroupPage(
  title: string,
  tasks: readonly TaskSummary[],
  fromDir: "by-status" | "by-tag" | "by-owner",
): string {
  const lines = [
    GENERATED_NOTE,
    "",
    `# ${title}`,
    "",
    "[Index](../index.md) | [All tasks](../tasks.md)",
    "",
    ...renderTaskTable(sortTasks(tasks), fromDir),
  ];
  return `${lines.join("\n").trimEnd()}\n`;
}

export function renderObsidianTaskProjection(
  tasks: readonly TaskSummary[],
): ObsidianProjectionResult {
  const sortedTasks = sortTasks(tasks);
  const statuses = groupBy(sortedTasks, (task) => [String(task.status || "unknown")]);
  const tags = groupBy(sortedTasks, (task) => {
    const values = taskTags(task);
    return values.length > 0 ? values : ["untagged"];
  });
  const owners = groupBy(sortedTasks, (task) => [String(task.owner || "unowned")]);

  const usedPaths = new Set<string>(["index.md", "tasks.md"]);
  const statusPaths = new Map<string, string>();
  const tagPaths = new Map<string, string>();
  const ownerPaths = new Map<string, string>();

  for (const status of orderedStatusKeys(statuses.keys())) {
    statusPaths.set(status, uniqueGroupPath("by-status", status, usedPaths, "unknown"));
  }
  for (const tag of [...tags.keys()].toSorted((a, b) => a.localeCompare(b))) {
    tagPaths.set(tag, uniqueGroupPath("by-tag", tag, usedPaths, "untagged"));
  }
  for (const owner of [...owners.keys()].toSorted((a, b) => a.localeCompare(b))) {
    ownerPaths.set(owner, uniqueGroupPath("by-owner", owner, usedPaths, "unowned"));
  }

  const files: ObsidianProjectionFile[] = [
    {
      path: "index.md",
      content: renderIndex(sortedTasks, {
        statuses: statusPaths,
        tags: tagPaths,
        owners: ownerPaths,
      }),
    },
    { path: "tasks.md", content: renderTaskList(sortedTasks) },
  ];

  for (const [status, filePath] of statusPaths) {
    files.push({
      path: filePath,
      content: renderGroupPage(`Status: ${status}`, statuses.get(status) ?? [], "by-status"),
    });
  }
  for (const [tag, filePath] of tagPaths) {
    files.push({
      path: filePath,
      content: renderGroupPage(`Tag: ${tag}`, tags.get(tag) ?? [], "by-tag"),
    });
  }
  for (const [owner, filePath] of ownerPaths) {
    files.push({
      path: filePath,
      content: renderGroupPage(`Owner: ${owner}`, owners.get(owner) ?? [], "by-owner"),
    });
  }

  return { files, taskCount: sortedTasks.length };
}

export async function writeObsidianTaskProjection(opts: {
  root: string;
  tasks: readonly TaskSummary[];
}): Promise<ObsidianProjectionResult> {
  const projection = renderObsidianTaskProjection(opts.tasks);
  const projectionDir = path.join(opts.root, OBSIDIAN_PROJECTION_DIR);
  await mkdir(projectionDir, { recursive: true });
  await Promise.all(
    OBSIDIAN_GROUP_DIRS.map((dir) => removeGeneratedGroupPages(path.join(projectionDir, dir))),
  );
  for (const file of projection.files) {
    const outputPath = path.join(projectionDir, file.path);
    await mkdir(path.dirname(outputPath), { recursive: true });
    await atomicWriteFile(outputPath, file.content);
  }
  await cleanLegacyObsidianTaskProjection(opts.root);
  return projection;
}

async function removeGeneratedGroupPages(dirPath: string): Promise<string[]> {
  let entries: Dirent[];
  try {
    entries = await readdir(dirPath, { withFileTypes: true });
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return [];
    throw error;
  }

  const deleted = await Promise.all(
    entries
      .filter((entry) => entry.isFile() && entry.name.endsWith(".md"))
      .map(async (entry) => {
        const filePath = path.join(dirPath, entry.name);
        const text = await readFile(filePath, "utf8");
        if (text.startsWith(GENERATED_NOTE)) {
          await rm(filePath, { force: true });
          return filePath;
        }
        return null;
      }),
  );
  return deleted.filter((filePath): filePath is string => filePath !== null);
}

async function removeEmptyDir(dirPath: string): Promise<boolean> {
  try {
    await rmdir(dirPath);
    return true;
  } catch (error) {
    const code = (error as NodeJS.ErrnoException).code;
    if (code === "ENOENT" || code === "ENOTEMPTY" || code === "EEXIST") return false;
    throw error;
  }
}

async function removeGeneratedFile(filePath: string): Promise<"deleted" | "preserved" | "missing"> {
  let text: string;
  try {
    text = await readFile(filePath, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return "missing";
    throw error;
  }
  if (!text.startsWith(GENERATED_NOTE)) return "preserved";
  await rm(filePath, { force: true });
  return "deleted";
}

export async function cleanObsidianTaskProjection(opts: {
  root: string;
}): Promise<ObsidianCleanResult> {
  const projectionDir = path.join(opts.root, OBSIDIAN_PROJECTION_DIR);
  const deleted: string[] = [];
  const preserved: string[] = [];

  for (const fileName of ["index.md", "tasks.md"]) {
    const filePath = path.join(projectionDir, fileName);
    const state = await removeGeneratedFile(filePath);
    if (state === "deleted") deleted.push(path.join(OBSIDIAN_PROJECTION_DIR, fileName));
    if (state === "preserved") preserved.push(path.join(OBSIDIAN_PROJECTION_DIR, fileName));
  }

  for (const dir of OBSIDIAN_GROUP_DIRS) {
    const dirPath = path.join(projectionDir, dir);
    const removedFiles = await removeGeneratedGroupPages(dirPath);
    deleted.push(...removedFiles.map((filePath) => path.relative(opts.root, filePath)));
    if (await removeEmptyDir(dirPath)) deleted.push(path.join(OBSIDIAN_PROJECTION_DIR, dir));
  }

  const legacy = await cleanLegacyObsidianTaskProjection(opts.root);
  deleted.push(...legacy.deleted);
  preserved.push(...legacy.preserved);

  return { deleted, preserved };
}

async function cleanLegacyObsidianTaskProjection(root: string): Promise<ObsidianCleanResult> {
  const agentplaneDir = path.join(root, ".agentplane");
  const deleted: string[] = [];
  const preserved: string[] = [];

  for (const fileName of ["index.md", "tasks.md"]) {
    const filePath = path.join(agentplaneDir, fileName);
    const state = await removeGeneratedFile(filePath);
    if (state === "deleted") deleted.push(path.join(".agentplane", fileName));
    if (state === "preserved") preserved.push(path.join(".agentplane", fileName));
  }

  for (const dir of OBSIDIAN_GROUP_DIRS) {
    const dirPath = path.join(agentplaneDir, dir);
    const removedFiles = await removeGeneratedGroupPages(dirPath);
    deleted.push(...removedFiles.map((filePath) => path.relative(root, filePath)));
    if (await removeEmptyDir(dirPath)) deleted.push(path.join(".agentplane", dir));
  }

  return { deleted, preserved };
}

async function listProjectionTasks(ctx: CommandContext): Promise<TaskSummary[]> {
  if (ctx.memo.taskProjection) return await ctx.memo.taskProjection;
  const read = async () => {
    if (ctx.taskBackend.listProjectionTasks) return await ctx.taskBackend.listProjectionTasks();
    return toTaskSummaries(await ctx.taskBackend.listTasks());
  };
  ctx.memo.taskProjection = read();
  return await ctx.memo.taskProjection;
}

export async function cmdTaskObsidian(opts: {
  ctx?: CommandContext;
  cwd: string;
  rootOverride?: string | null;
  strictRead?: boolean;
}): Promise<number> {
  try {
    const ctx =
      opts.ctx ??
      (await loadCommandContext({ cwd: opts.cwd, rootOverride: opts.rootOverride ?? null }));
    const tasks = await listProjectionTasks(ctx);
    handleTaskListWarnings({ backend: ctx.taskBackend, strictRead: opts.strictRead });
    const result = await writeObsidianTaskProjection({
      root: ctx.resolvedProject.gitRoot,
      tasks,
    });
    process.stdout.write(
      `${OBSIDIAN_PROJECTION_DIR}/index.md\n${OBSIDIAN_PROJECTION_DIR}/tasks.md\nfiles=${result.files.length} tasks=${result.taskCount}\n`,
    );
    return 0;
  } catch (err) {
    throw mapBackendError(err, { command: "task obsidian", root: opts.rootOverride ?? null });
  }
}

export async function cmdTaskObsidianClean(opts: {
  ctx?: CommandContext;
  cwd: string;
  rootOverride?: string | null;
}): Promise<number> {
  try {
    const ctx =
      opts.ctx ??
      (await loadCommandContext({ cwd: opts.cwd, rootOverride: opts.rootOverride ?? null }));
    const result = await cleanObsidianTaskProjection({ root: ctx.resolvedProject.gitRoot });
    process.stdout.write(`deleted=${result.deleted.length} preserved=${result.preserved.length}\n`);
    return 0;
  } catch (err) {
    throw mapBackendError(err, { command: "task obsidian clean", root: opts.rootOverride ?? null });
  }
}
