// Thin public re-export layer: keep CLI imports stable while command implementations live by domain.

export const IDE_SYNC_USAGE = "Usage: agentplane ide sync";
export const IDE_SYNC_USAGE_EXAMPLE = "agentplane ide sync";

export {
  TASK_NEW_USAGE,
  TASK_NEW_USAGE_EXAMPLE,
  TASK_ADD_USAGE,
  TASK_ADD_USAGE_EXAMPLE,
  TASK_SCRUB_USAGE,
  TASK_SCRUB_USAGE_EXAMPLE,
  TASK_UPDATE_USAGE,
  TASK_UPDATE_USAGE_EXAMPLE,
  TASK_SCAFFOLD_USAGE,
  TASK_SCAFFOLD_USAGE_EXAMPLE,
  TASK_DOC_SET_USAGE,
  TASK_DOC_SET_USAGE_EXAMPLE,
  TASK_DOC_SHOW_USAGE,
  TASK_DOC_SHOW_USAGE_EXAMPLE,
  START_USAGE,
  START_USAGE_EXAMPLE,
  BLOCK_USAGE,
  BLOCK_USAGE_EXAMPLE,
  FINISH_USAGE,
  FINISH_USAGE_EXAMPLE,
  VERIFY_USAGE,
  VERIFY_USAGE_EXAMPLE,
  dedupeStrings,
  cmdTaskNew,
  cmdTaskAdd,
  cmdTaskUpdate,
  cmdTaskScrub,
  cmdTaskListWithFilters,
  cmdTaskNext,
  cmdReady,
  cmdTaskSearch,
  cmdTaskScaffold,
  cmdTaskNormalize,
  cmdTaskMigrate,
  cmdTaskComment,
  cmdTaskSetStatus,
  cmdTaskShow,
  cmdTaskList,
  cmdTaskExport,
  cmdTaskLint,
  cmdTaskDocSet,
  cmdTaskDocShow,
  cmdStart,
  cmdBlock,
  cmdFinish,
  cmdVerify,
} from "./task/index.js";

export {
  BRANCH_BASE_USAGE,
  BRANCH_BASE_USAGE_EXAMPLE,
  BRANCH_STATUS_USAGE,
  BRANCH_STATUS_USAGE_EXAMPLE,
  BRANCH_REMOVE_USAGE,
  BRANCH_REMOVE_USAGE_EXAMPLE,
  WORK_START_USAGE,
  WORK_START_USAGE_EXAMPLE,
  CLEANUP_MERGED_USAGE,
  CLEANUP_MERGED_USAGE_EXAMPLE,
  gitInitRepo,
  resolveInitBaseBranch,
  promptInitBaseBranch,
  ensureInitCommit,
  cmdWorkStart,
  cmdCleanupMerged,
  cmdBranchBaseGet,
  cmdBranchBaseSet,
  cmdBranchBaseClear,
  cmdBranchBaseExplain,
  cmdBranchStatus,
  cmdBranchRemove,
} from "./branch/index.js";

export {
  PR_OPEN_USAGE,
  PR_OPEN_USAGE_EXAMPLE,
  PR_UPDATE_USAGE,
  PR_UPDATE_USAGE_EXAMPLE,
  PR_CHECK_USAGE,
  PR_CHECK_USAGE_EXAMPLE,
  PR_NOTE_USAGE,
  PR_NOTE_USAGE_EXAMPLE,
  INTEGRATE_USAGE,
  INTEGRATE_USAGE_EXAMPLE,
  cmdPrOpen,
  cmdPrUpdate,
  cmdPrCheck,
  cmdPrNote,
  cmdIntegrate,
} from "./pr/index.js";

export {
  GUARD_COMMIT_USAGE,
  GUARD_COMMIT_USAGE_EXAMPLE,
  COMMIT_USAGE,
  COMMIT_USAGE_EXAMPLE,
  suggestAllowPrefixes,
  cmdGuardClean,
  cmdGuardSuggestAllow,
  cmdGuardCommit,
  cmdCommit,
} from "./guard/index.js";

export { HOOK_NAMES, cmdHooksInstall, cmdHooksUninstall, cmdHooksRun } from "./hooks/index.js";
