export const RUNTIME_GITIGNORE_LINES = [
  "# agentplane: ignore runtime/transient workspace artifacts",
  ".env",
  ".agentplane/worktrees",
  ".agentplane/local-backups",
  ".agentplane/cache",
  ".agentplane/cache.sqlite",
  ".agentplane/cache.sqlite-wal",
  ".agentplane/cache.sqlite-shm",
  ".agentplane/recipes-cache",
  ".agentplane/generated/obsidian",
  ".agentplane/.upgrade",
  ".agentplane/.release",
  ".agentplane/upgrade",
  ".agentplane/tasks.json",
  ".agentplane/index.md",
  ".agentplane/tasks.md",
  ".agentplane/by-status",
  ".agentplane/by-tag",
  ".agentplane/by-owner",
  ".agentplane/tasks/*/handoff",
  "AGENTS.md.bak-*",
  "CLAUDE.md.bak-*",
  ".agentplane/agents/*.bak-*",
  ".agentplane/policy/**/*.bak-*",
] as const;

export const AGENT_PROMPT_GITIGNORE_LINES = [
  "# agentplane: ignore local agent prompts/templates",
  "AGENTS.md",
  "CLAUDE.md",
  ".agentplane/agents/",
  ".agentplane/evaluators/",
  ".agentplane/policy/",
] as const;
