import { gitRevParse } from "@agentplaneorg/core/git";
import { setMarkdownSection } from "@agentplaneorg/core/tasks";
import path from "node:path";

import { writeAcrFile } from "../../../../commands/acr/acr.command.js";
import { generateAcr } from "../../../../commands/acr/generate.js";
import type { TaskData } from "../../../../backends/task-backend.js";
import type { CommandContext } from "../../../../commands/shared/task-backend.js";
import { TASK_DOC_VERSION_V3, defaultTaskDocV3 } from "../../../../commands/task/doc-template.js";
import { nowIso } from "../../../../commands/task/shared.js";
import { createCliEmitter } from "../../../output.js";
import type { CommandCtx, CommandHandler, CommandSpec } from "../../../spec/spec.js";

const output = createCliEmitter();

type DemoParsed = {
  json: boolean;
  dryRun: boolean;
};

type DemoResult = {
  taskId: string;
  taskPath: string;
  acrPath: string;
  nextCommand: string;
};

export const demoSpec: CommandSpec<DemoParsed> = {
  id: ["demo"],
  group: "Core",
  summary: "Create a safe first-success Agentplane demo task with ACR evidence.",
  description:
    "Creates an inspectable demo task under .agentplane/tasks without touching user source files, network, or GitHub.",
  options: [
    {
      kind: "boolean",
      name: "dry-run",
      default: false,
      description: "Preview the files and commands without writing demo artifacts.",
    },
    {
      kind: "boolean",
      name: "json",
      default: false,
      description: "Emit compact machine-readable output for agent runtimes.",
    },
  ],
  examples: [
    { cmd: "agentplane demo", why: "Create a first-success task artifact and ACR." },
    { cmd: "agentplane demo --dry-run", why: "Preview the first-success path." },
  ],
  parse: (raw) => ({
    dryRun: raw.opts["dry-run"] === true,
    json: raw.opts.json === true,
  }),
};

function demoDescription(): string {
  return [
    "Create a harmless Agentplane demo task that shows the normal audit trail:",
    "plan approval, start event, verification evidence, finish state, and ACR artifact.",
  ].join(" ");
}

function buildDemoDoc(title: string, description: string): string {
  let doc = defaultTaskDocV3({ title, description });
  doc = setMarkdownSection(
    doc,
    "Plan",
    [
      "1. Create a harmless demo task that mutates only Agentplane task artifacts.",
      "2. Record the normal lifecycle evidence in the task README.",
      "3. Generate a task-local ACR so the first success is inspectable.",
    ].join("\n"),
  );
  doc = setMarkdownSection(
    doc,
    "Verify Steps",
    [
      "1. Inspect this README. Expected: plan, verification, rollback, and findings sections are present.",
      "2. Inspect `acr.json`. Expected: it references this task and repository commit range.",
      "3. Run `agentplane acr validate <task-id> --mode local`. Expected: the ACR validates locally.",
    ].join("\n"),
  );
  doc = setMarkdownSection(
    doc,
    "Verification",
    [
      "<!-- BEGIN VERIFICATION RESULTS -->",
      "### DEMO - VERIFY - ok",
      "",
      "By: DEMO",
      "",
      "Note: Demo task generated by `agentplane demo`; no user source files, network, or GitHub state were required.",
      "<!-- END VERIFICATION RESULTS -->",
    ].join("\n"),
  );
  doc = setMarkdownSection(
    doc,
    "Findings",
    [
      "- Observation: `agentplane demo` generated this task as a first-success artifact.",
      "  Impact: Users can inspect Agentplane evidence before giving an agent broad edit scope.",
      "  Resolution: Use this task README and ACR as the local audit trail preview.",
    ].join("\n"),
  );
  return doc;
}

async function createDemoTask(ctx: CommandContext): Promise<DemoResult> {
  await ctx.taskBackend.assertLocalMutationReady?.();
  if (!ctx.taskBackend.generateTaskId) {
    throw new Error("Current task backend does not support demo task id generation.");
  }

  const taskId = await ctx.taskBackend.generateTaskId({ length: 6, attempts: 1000 });
  const now = nowIso();
  const title = "Agentplane demo: first traceable task";
  const description = demoDescription();
  const head = await gitRevParse(ctx.resolvedProject.gitRoot, ["HEAD"]).catch(() => "HEAD");
  const doc = buildDemoDoc(title, description);
  const task: TaskData = {
    id: taskId,
    title,
    description,
    result_summary: "Demo task generated a first-success Agentplane audit trail.",
    status: "DONE",
    priority: "low",
    owner: "DEMO",
    revision: 1,
    origin: { system: "agentplane-demo" },
    depends_on: [],
    tags: ["demo", "docs"],
    task_kind: "docs",
    mutation_scope: "docs",
    verify: ["agentplane acr validate <task-id> --mode local"],
    plan_approval: {
      state: "approved",
      updated_at: now,
      updated_by: "DEMO",
      note: "Demo task auto-approves its harmless artifact-only scope.",
    },
    verification: {
      state: "ok",
      updated_at: now,
      updated_by: "DEMO",
      note: "Demo artifacts generated successfully without user-source or network mutation.",
      attempts: 1,
    },
    commit: { hash: head, message: "Demo task references current repository HEAD" },
    comments: [
      {
        author: "DEMO",
        body: "Start: generated a harmless first-success task artifact through `agentplane demo`.",
      },
      {
        author: "DEMO",
        body: "Verified: demo task README and ACR evidence were generated for local inspection.",
      },
    ],
    events: [
      {
        type: "status",
        at: now,
        author: "DEMO",
        from: "TODO",
        to: "DOING",
        note: "Start: generated a harmless first-success task artifact through `agentplane demo`.",
      },
      {
        type: "verify",
        at: now,
        author: "DEMO",
        state: "ok",
        note: "Demo task README and ACR evidence were generated for local inspection.",
      },
      {
        type: "status",
        at: now,
        author: "DEMO",
        from: "DOING",
        to: "DONE",
        note: "Verified: demo task README and ACR evidence were generated for local inspection.",
      },
    ],
    doc,
    doc_version: TASK_DOC_VERSION_V3,
    doc_updated_at: now,
    doc_updated_by: "DEMO",
    id_source: "generated",
  };

  await ctx.taskBackend.writeTask(task);
  const { record, acrPath } = await generateAcr({
    ctx,
    cwd: ctx.resolvedProject.gitRoot,
    taskId,
    workCommit: head,
    baseCommit: head,
    agent: "DEMO",
    agentName: "Agentplane Demo",
    modelProvider: "unknown",
    modelName: "demo",
    write: true,
    refresh: true,
  });
  if (!acrPath) throw new Error("ACR generation did not resolve a task-local output path.");
  await writeAcrFile({ acrPath, record, refresh: true });

  return {
    taskId,
    taskPath: path.join(ctx.config.paths.workflow_dir, taskId, "README.md"),
    acrPath: path.relative(ctx.resolvedProject.gitRoot, acrPath),
    nextCommand: `agentplane acr validate ${taskId} --mode local`,
  };
}

function renderText(result: DemoResult): void {
  output.report(
    [
      { label: "task", value: result.taskId },
      { label: "task_readme", value: result.taskPath },
      { label: "acr", value: result.acrPath },
      { label: "next", value: result.nextCommand },
    ],
    { header: "Agentplane demo" },
  );
}

export function makeRunDemoHandler(getCtx: (cmd: string) => Promise<CommandContext>) {
  return async (_cmdCtx: CommandCtx, parsed: DemoParsed): Promise<number> => {
    const ctx = await getCtx("demo");
    const preview: DemoResult = {
      taskId: "<generated>",
      taskPath: path.join(ctx.config.paths.workflow_dir, "<task-id>", "README.md"),
      acrPath: path.join(ctx.config.paths.workflow_dir, "<task-id>", "acr.json"),
      nextCommand: "agentplane acr validate <task-id> --mode local",
    };

    if (parsed.dryRun) {
      if (parsed.json) output.json({ ok: true, command: "demo", dry_run: true, ...preview });
      else renderText(preview);
      return 0;
    }

    const result = await createDemoTask(ctx);
    if (parsed.json) output.json({ ok: true, command: "demo", dry_run: false, ...result });
    else renderText(result);
    return 0;
  };
}

export const runDemo: CommandHandler<DemoParsed> = async (ctx, parsed) => {
  const { loadCommandContext } = await import("../../../../commands/shared/task-backend.js");
  const commandContext = await loadCommandContext({
    cwd: ctx.cwd,
    rootOverride: ctx.rootOverride ?? null,
  });
  return await makeRunDemoHandler(() => Promise.resolve(commandContext))(ctx, parsed);
};
