import { gitRevParse } from "@agentplaneorg/core/git";
import { setMarkdownSection, taskKernel as k } from "@agentplaneorg/core/tasks";
import path from "node:path";

import { writeAcrFile } from "../../../../commands/acr/acr.command.js";
import { generateAcr } from "../../../../commands/acr/generate.js";
import type { TaskData } from "../../../../backends/task-backend.js";
import type { CommandContext } from "../../../../commands/shared/task-backend.js";
import { createCanonicalTask } from "../../../../commands/task/kernel-create.js";
import { setCanonicalPlan } from "../../../../commands/task/kernel-plan.js";
import {
  createKernelRuntime,
  type KernelCommandPayload,
  requireKernelCommit,
} from "../../../../commands/task/kernel-runtime-context.js";
import { TASK_DOC_VERSION_V3, defaultTaskDocV3 } from "../../../../commands/task/doc-template.js";
import { nowIso } from "../../../../commands/task/shared.js";
import {
  resolveTaskExecutionContract,
  resolveTaskExecutionRoute,
} from "../../../../runtime/task-routing/index.js";
import { createCliEmitter } from "../../../output.js";
import type { CommandCtx, CommandHandler, CommandSpec } from "../../../spec/spec.js";

const output = createCliEmitter();

type DemoParsed = {
  json: boolean;
  dryRun: boolean;
};

type DemoResult = {
  taskId: string;
  taskPath: string;
  acrPath: string;
  nextCommand: string;
};

export const demoSpec: CommandSpec<DemoParsed> = {
  id: ["demo"],
  group: "Core",
  summary: "Create a safe first-success Agentplane demo task with ACR evidence.",
  description:
    "Creates an inspectable demo task under .agentplane/tasks without touching user source files, network, or GitHub.",
  options: [
    {
      kind: "boolean",
      name: "dry-run",
      default: false,
      description: "Preview the files and commands without writing demo artifacts.",
    },
    {
      kind: "boolean",
      name: "json",
      default: false,
      description: "Emit compact machine-readable output for agent runtimes.",
    },
  ],
  examples: [
    { cmd: "agentplane demo", why: "Create a first-success task artifact and ACR." },
    { cmd: "agentplane demo --dry-run", why: "Preview the first-success path." },
  ],
  parse: (raw) => ({
    dryRun: raw.opts["dry-run"] === true,
    json: raw.opts.json === true,
  }),
};

function demoDescription(): string {
  return [
    "Create a harmless Agentplane demo task that shows the normal audit trail:",
    "plan approval, start event, verification evidence, finish state, and ACR artifact.",
  ].join(" ");
}

function buildDemoDoc(title: string, description: string): string {
  let doc = defaultTaskDocV3({ title, description });
  doc = setMarkdownSection(
    doc,
    "Plan",
    [
      "1. Create a harmless demo task that mutates only Agentplane task artifacts.",
      "2. Record the normal lifecycle evidence in the task README.",
      "3. Generate a task-local ACR so the first success is inspectable.",
    ].join("\n"),
  );
  doc = setMarkdownSection(
    doc,
    "Verify Steps",
    [
      "1. Inspect this README. Expected: plan, verification, rollback, and findings sections are present.",
      "2. Inspect `acr.json`. Expected: it references this task and repository commit range.",
      "3. Run `agentplane acr validate <task-id> --mode local`. Expected: the ACR validates locally.",
    ].join("\n"),
  );
  doc = setMarkdownSection(
    doc,
    "Verification",
    [
      "<!-- BEGIN VERIFICATION RESULTS -->",
      "### DEMO - VERIFY - ok",
      "",
      "By: DEMO",
      "",
      "Note: Demo task generated by `agentplane demo`; no user source files, network, or GitHub state were required.",
      "<!-- END VERIFICATION RESULTS -->",
    ].join("\n"),
  );
  doc = setMarkdownSection(
    doc,
    "Findings",
    [
      "- Observation: `agentplane demo` generated this task as a first-success artifact.",
      "  Impact: Users can inspect Agentplane evidence before giving an agent broad edit scope.",
      "  Resolution: Use this task README and ACR as the local audit trail preview.",
    ].join("\n"),
  );
  return doc;
}

async function completeCanonicalDemoTask(ctx: CommandContext, task: TaskData): Promise<void> {
  await createCanonicalTask(ctx, task);
  const taskId = task.id;
  await setCanonicalPlan(ctx, taskId, {
    work_items: [
      {
        id: "demo-audit-trail",
        depends_on: [],
        required_inputs: [],
        expected_outputs: ["demo-audit-trail"],
        execution_requirements: {
          scope_roots: [ctx.config.paths.workflow_dir],
          repository_effects: ["agentplane_task_artifacts"],
          external_effects: [],
          capabilities: ["repository_write"],
          resources: [`task:${taskId}`],
        },
        optional: false,
        contract: {
          objective: "Create the inspectable Agentplane demo audit trail.",
          acceptance_criteria: [
            "The task README records plan and verification evidence.",
            "The task-local ACR references the canonical demo task.",
          ],
          verification_commands: [`agentplane acr validate ${taskId} --mode local`],
          role: "EXECUTOR",
        },
      },
    ],
  });

  const runtime = await createKernelRuntime({
    command: ctx,
    task_id: taskId,
    transport: "manual",
    operation_id: `demo:${taskId}`,
    approval: {
      kind: "manual_operator",
      actor_id: "USER:DEMO",
      invocation_id: `agentplane-demo:${taskId}`,
    },
  });
  await runtime.checkpoint(await runtime.observe());
  const approved = requireKernelCommit(await runtime.authority.approve(taskId));
  const plan = approved.record.aggregate.current_plan;
  if (!plan || plan.state !== "APPROVED") {
    throw new Error("Demo canonical plan approval was not persisted.");
  }

  const refreshAuthority = async (): Promise<void> => {
    for (let attempt = 0; attempt < 4; attempt += 1) {
      const [read, context] = await Promise.all([
        runtime.adapter.read(taskId),
        runtime.native.readContext(taskId),
      ]);
      if (read.kind !== "canonical") throw new Error("Demo canonical task readback unavailable.");
      const authority = read.record.aggregate.authority_lineage?.at(-1)?.authority;
      if (authority?.repository_fingerprint === context.repository_fingerprint) return;
      requireKernelCommit(await runtime.authority.continue(taskId));
    }
    throw new Error("Demo canonical authority did not converge on the current repository state.");
  };
  const input = async (payload: KernelCommandPayload, mutationId: string) => {
    await refreshAuthority();
    await runtime.checkpoint(await runtime.observe());
    return await runtime.input(payload, mutationId);
  };
  const apply = async (payload: KernelCommandPayload, mutationId: string) =>
    requireKernelCommit(await runtime.lifecycle.apply(await input(payload, mutationId)));

  await apply(
    {
      kind: "materialize_work_items",
      plan_revision: plan.revision,
      plan_digest: plan.digest,
    },
    `demo:${taskId}:materialize`,
  );
  const claimId = k.kernelDigest({ task_id: taskId, work_item_id: "demo-audit-trail" });
  await apply(
    {
      kind: "transition_work_item",
      action: "claim",
      work_item_id: "demo-audit-trail",
      claim_id: claimId,
    },
    `demo:${taskId}:claim`,
  );
  const begun = await runtime.lifecycle.begin(
    await input(
      {
        kind: "transition_work_item",
        action: "begin",
        work_item_id: "demo-audit-trail",
        claim_id: claimId,
      },
      `demo:${taskId}:begin`,
    ),
  );
  requireKernelCommit(begun.result);
  if (!begun.work_order) throw new Error("Demo canonical WorkOrder was not created.");

  const resultDigest = k.kernelDigest({ task_id: taskId, result: "demo-audit-trail" });
  await refreshAuthority();
  await runtime.checkpoint(await runtime.observe());
  const resultContext = await runtime.native.readContext(taskId);
  const resultInput = await runtime.input(
    {
      kind: "accept_work_item_result",
      plan_revision: plan.revision,
      plan_digest: plan.digest,
      work_item_id: "demo-audit-trail",
      result_digest: resultDigest,
      output_manifests: [
        {
          id: "demo-audit-trail",
          kind: "agentplane.demo.audit",
          digest: resultDigest,
          task_id: taskId,
          plan_revision: plan.revision,
          work_item_id: "demo-audit-trail",
          attempt: begun.work_order.binding.attempt,
          repository_fingerprint: resultContext.repository_fingerprint,
        },
      ],
    },
    `demo:${taskId}:result`,
  );
  requireKernelCommit(await runtime.lifecycle.receiveResult(resultInput, begun.work_order.binding));
  await apply(
    {
      kind: "transition_work_item",
      action: "inspect",
      work_item_id: "demo-audit-trail",
      claim_id: claimId,
    },
    `demo:${taskId}:inspect`,
  );
  const observedAt = new Date().toISOString();
  await apply(
    {
      kind: "record_work_item_validation",
      work_item_id: "demo-audit-trail",
      validation: {
        status: "PASSED",
        identity: {
          implementation_identity: resultDigest,
          check_id: "agentplane-demo",
          command_digest: k.kernelDigest(`agentplane acr validate ${taskId} --mode local`),
          toolchain_digest: k.kernelDigest("agentplane-demo"),
          environment_digest: resultContext.repository_fingerprint,
        },
        evidence_digests: [resultDigest],
        observed_at: observedAt,
      },
    },
    `demo:${taskId}:validate`,
  );
  await apply(
    {
      kind: "transition_work_item",
      action: "complete",
      work_item_id: "demo-audit-trail",
      claim_id: claimId,
    },
    `demo:${taskId}:complete-work-item`,
  );

  await refreshAuthority();
  await runtime.checkpoint(await runtime.observe());
  const finalContext = await runtime.native.readContext(taskId);
  const finalEvidence = k.kernelDigest({ task_id: taskId, result_digest: resultDigest });
  requireKernelCommit(
    await runtime.lifecycle.apply(
      await runtime.input(
        {
          kind: "record_final_validation",
          validation: {
            status: "PASSED",
            identity: {
              implementation_identity: finalContext.repository_fingerprint,
              check_id: "agentplane-demo-final",
              command_digest: k.kernelDigest(`agentplane acr validate ${taskId} --mode local`),
              toolchain_digest: k.kernelDigest("agentplane-demo"),
              environment_digest: finalContext.repository_fingerprint,
            },
            evidence_digests: [finalEvidence],
            observed_at: observedAt,
          },
        },
        `demo:${taskId}:final-validation`,
      ),
    ),
  );
  await apply({ kind: "complete_task" }, `demo:${taskId}:complete-task`);

  const completed = await runtime.adapter.read(taskId);
  if (completed.kind !== "canonical" || completed.record.aggregate.state !== "COMPLETED") {
    throw new Error("Demo canonical task completion was not persisted.");
  }
}

async function createDemoTask(ctx: CommandContext): Promise<DemoResult> {
  await ctx.taskBackend.assertLocalMutationReady?.();
  if (!ctx.taskBackend.generateTaskId) {
    throw new Error("Current task backend does not support demo task id generation.");
  }

  const taskId = await ctx.taskBackend.generateTaskId({ length: 6, attempts: 1000 });
  const now = nowIso();
  const title = "Agentplane demo: first traceable task";
  const description = demoDescription();
  const head = await gitRevParse(ctx.resolvedProject.gitRoot, ["HEAD"]).catch(() => "HEAD");
  const doc = buildDemoDoc(title, description);
  const routeTask = {
    task_kind: "docs" as const,
    mutation_scope: "docs" as const,
    risk_flags: [],
  };
  const executionContract = resolveTaskExecutionContract({
    config: ctx.config,
    requestedMode: "direct",
    task: routeTask,
  });
  const task: TaskData = {
    id: taskId,
    title,
    description,
    result_summary: "Demo task generated a first-success Agentplane audit trail.",
    status: "DONE",
    priority: "low",
    owner: "DEMO",
    revision: 1,
    origin: { system: "agentplane-demo" },
    depends_on: [],
    tags: ["demo", "docs"],
    task_kind: "docs",
    mutation_scope: "docs",
    execution_route: resolveTaskExecutionRoute({
      config: ctx.config,
      requestedMode: "direct",
      task: routeTask,
    }),
    execution_contract: executionContract,
    verify: ["agentplane acr validate <task-id> --mode local"],
    plan_approval: {
      state: "approved",
      updated_at: now,
      updated_by: "DEMO",
      note: "Demo task auto-approves its harmless artifact-only scope.",
    },
    verification: {
      state: "ok",
      updated_at: now,
      updated_by: "DEMO",
      note: "Demo artifacts generated successfully without user-source or network mutation.",
      attempts: 1,
    },
    commit: { hash: head, message: "Demo task references current repository HEAD" },
    comments: [
      {
        author: "DEMO",
        body: "Start: generated a harmless first-success task artifact through `agentplane demo`.",
      },
      {
        author: "DEMO",
        body: "Verified: demo task README and ACR evidence were generated for local inspection.",
      },
    ],
    events: [
      {
        type: "status",
        at: now,
        author: "DEMO",
        from: "TODO",
        to: "DOING",
        note: "Start: generated a harmless first-success task artifact through `agentplane demo`.",
      },
      {
        type: "verify",
        at: now,
        author: "DEMO",
        state: "ok",
        note: "Demo task README and ACR evidence were generated for local inspection.",
      },
      {
        type: "status",
        at: now,
        author: "DEMO",
        from: "DOING",
        to: "DONE",
        note: "Verified: demo task README and ACR evidence were generated for local inspection.",
      },
    ],
    doc,
    doc_version: TASK_DOC_VERSION_V3,
    doc_updated_at: now,
    doc_updated_by: "DEMO",
    id_source: "generated",
  };

  await completeCanonicalDemoTask(ctx, task);
  const { record, acrPath } = await generateAcr({
    ctx,
    cwd: ctx.resolvedProject.gitRoot,
    taskId,
    workCommit: head,
    baseCommit: head,
    agent: "DEMO",
    agentName: "Agentplane Demo",
    modelProvider: "unknown",
    modelName: "demo",
    write: true,
    refresh: true,
  });
  if (!acrPath) throw new Error("ACR generation did not resolve a task-local output path.");
  await writeAcrFile({ acrPath, record, refresh: true });

  return {
    taskId,
    taskPath: path.join(ctx.config.paths.workflow_dir, taskId, "README.md"),
    acrPath: path.relative(ctx.resolvedProject.gitRoot, acrPath),
    nextCommand: `agentplane acr validate ${taskId} --mode local`,
  };
}

function renderText(result: DemoResult): void {
  output.report(
    [
      { label: "task", value: result.taskId },
      { label: "task_readme", value: result.taskPath },
      { label: "acr", value: result.acrPath },
      { label: "next", value: result.nextCommand },
    ],
    { header: "Agentplane demo" },
  );
}

export function makeRunDemoHandler(getCtx: (cmd: string) => Promise<CommandContext>) {
  return async (_cmdCtx: CommandCtx, parsed: DemoParsed): Promise<number> => {
    const ctx = await getCtx("demo");
    const preview: DemoResult = {
      taskId: "<generated>",
      taskPath: path.join(ctx.config.paths.workflow_dir, "<task-id>", "README.md"),
      acrPath: path.join(ctx.config.paths.workflow_dir, "<task-id>", "acr.json"),
      nextCommand: "agentplane acr validate <task-id> --mode local",
    };

    if (parsed.dryRun) {
      if (parsed.json) output.json({ ok: true, command: "demo", dry_run: true, ...preview });
      else renderText(preview);
      return 0;
    }

    const result = await createDemoTask(ctx);
    if (parsed.json) output.json({ ok: true, command: "demo", dry_run: false, ...result });
    else renderText(result);
    return 0;
  };
}

export const runDemo: CommandHandler<DemoParsed> = async (ctx, parsed) => {
  const { loadCommandContext } = await import("../../../../commands/shared/task-backend.js");
  const commandContext = await loadCommandContext({
    cwd: ctx.cwd,
    rootOverride: ctx.rootOverride ?? null,
  });
  return await makeRunDemoHandler(() => Promise.resolve(commandContext))(ctx, parsed);
};
