import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    "index",
    {
      type: "category",
      label: "User Guide",
      items: [
        "user/overview",
        "user/prerequisites",
        "user/setup",
        "user/breaking-changes",
        "user/workflow",
        "user/task-lifecycle",
        "user/agents",
        "user/branching-and-pr-artifacts",
        "user/tasks-and-backends",
        "user/backends",
        "user/backends/local",
        "user/backends/redmine",
        "user/redmine",
        "user/configuration",
        "user/commands",
        "user/cli-reference.generated",
      ],
    },
    {
      type: "category",
      label: "Website & Discovery",
      items: ["user/website-ia", "user/agent-discovery", "user/indexing-and-webmaster-operations"],
    },
    {
      type: "category",
      label: "Developer Guide",
      items: [
        "developer/design-principles",
        "developer/architecture",
        "developer/project-layout",
        "developer/documentation-information-architecture",
        "developer/cli-contract",
        "developer/cli-help-json",
        "developer/typescript-esm-imports",
        "developer/recipes-spec",
        "developer/recipes-how-it-works",
        "developer/recipes-development",
        "developer/recipes-safety",
        "developer/testing-and-quality",
        "developer/code-quality",
        "developer/release-and-publishing",
        "developer/contributing",
      ],
    },
    {
      type: "category",
      label: "Release Notes",
      items: [
        "releases/index",
        "releases/v0.2.24",
        "releases/v0.2.23",
        "releases/v0.2.22",
        "releases/v0.2.21",
        "releases/v0.2.20",
        "releases/v0.2.19",
        "releases/v0.2.18",
        "releases/v0.2.17",
        "releases/v0.2.16",
        "releases/v0.2.15",
        "releases/v0.2.14",
        "releases/v0.2.13",
        "releases/v0.2.12",
        "releases/v0.2.11",
        "releases/v0.2.10",
        "releases/v0.2.9",
        "releases/v0.2.8",
        "releases/v0.2.7",
        "releases/v0.2.6",
        "releases/v0.2.5",
        "releases/v0.2.4",
        "releases/v0.2.3",
        "releases/v0.2.2",
        "releases/v0.2.1",
        "releases/v0.2.0",
        "releases/v0.1.9",
        "releases/v0.1.8",
        "releases/v0.1.7",
        "releases/v0.1.6",
        "releases/v0.1.5",
        "releases/v0.1.4",
        "releases/v0.1.3",
      ],
    },
    {
      type: "category",
      label: "Help",
      items: ["help/troubleshooting-by-symptom", "help/troubleshooting", "help/glossary"],
    },
  ],
};

export default sidebars;
