export function renderHelp(): string {
  return [
    "agentplane (v1 prototype)",
    "",
    "Usage:",
    "  agentplane [--root <path>] [--json] [--no-update-check] <namespace> <command> [options]",
    "  agentplane [--root <path>] [--json] [--no-update-check] <command> [options]",
    "",
    "Core namespaces (implemented in this prototype): config, mode, task, ide, recipes, backend",
    "",
    "Flags:",
    "  --help, -h           Show help",
    "  --version            Show version",
    "  --root <path>        Treat <path> as project root",
    "  --no-update-check    Skip checking npm for a newer CLI version",
    "",
    "Quickstart commands:",
    "  agentplane quickstart",
    "",
    "Init commands:",
    "  agentplane init [--ide <codex|cursor|windsurf>] [--workflow <direct|branch_pr>] [--hooks <yes|no>] [--require-plan-approval <yes|no>] [--require-network-approval <yes|no>] [--require-verify-approval <yes|no>] [--recipes <list>] [--yes] [--force|--backup]",
    "",
    "Upgrade commands:",
    "  agentplane upgrade [--tag <tag>] [--dry-run] [--no-backup] [--source <repo-url>] [--bundle <path|url>] [--checksum <path|url>] [--yes]",
    "",
    "Config commands:",
    "  agentplane config show",
    "  agentplane config set <key> <value>",
    "",
    "Mode commands:",
    "  agentplane mode get",
    "  agentplane mode set <direct|branch_pr>",
    "",
    "IDE commands:",
    "  agentplane ide sync",
    "",
    "Recipe commands:",
    "  agentplane recipes list [--full] [--tag <tag>]",
    "  agentplane recipes list-remote [--refresh] [--index <path|url>] [--yes]",
    "  agentplane recipes info <id>",
    "  agentplane recipes explain <id>",
    "  agentplane recipes install --name <id> [--index <path|url>] [--refresh] [--yes]",
    "  agentplane recipes install --path <path> | --url <url> [--yes]",
    "  agentplane recipes remove <id>",
    "  agentplane recipes cache prune [--dry-run] [--all]",
    "  agentplane scenario list",
    "  agentplane scenario info <recipe:scenario>",
    "  agentplane scenario run <recipe:scenario>",
    "",
    "Backend commands:",
    "  agentplane backend sync <id> --direction <push|pull> [--conflict <diff|prefer-local|prefer-remote|fail>] [--yes] [--quiet]",
    "  agentplane sync [<id>] [--direction <push|pull>] [--conflict <diff|prefer-local|prefer-remote|fail>] [--yes] [--quiet]",
    "",
    "Branch commands:",
    "  agentplane branch base get",
    "  agentplane branch base set <name>",
    "  agentplane branch status [--branch <name>] [--base <name>]",
    "  agentplane branch remove [--branch <name>] [--worktree <path>] [--force] [--quiet]",
    "",
    "Work commands:",
    "  agentplane work start <task-id> --agent <id> --slug <slug> --worktree",
    "",
    "PR commands:",
    "  agentplane pr open <task-id> --author <id> [--branch <name>]",
    "  agentplane pr update <task-id>",
    "  agentplane pr check <task-id>",
    "  agentplane pr note <task-id> --author <id> --body <text>",
    "",
    "Integrate commands:",
    "  agentplane integrate <task-id> [--branch <name>] [--base <name>] [--merge-strategy squash|merge|rebase] [--run-verify] [--dry-run] [--quiet]",
    "",
    "Cleanup commands:",
    "  agentplane cleanup merged [--base <name>] [--yes] [--archive] [--quiet]",
    "",
    "Guard commands:",
    "  agentplane guard clean [--quiet]",
    "  agentplane guard suggest-allow [--format lines|args]",
    "  agentplane guard commit <task-id> -m <message> --allow <path> [--allow <path>...] [--auto-allow] [--allow-tasks] [--require-clean] [--quiet]",
    "",
    "Commit commands:",
    "  agentplane commit <task-id> -m <message> --allow <path> [--allow <path>...]",
    "  agentplane commit <task-id> -m <message> --auto-allow",
    "",
    "Hooks commands:",
    "  agentplane hooks install [--quiet]",
    "  agentplane hooks uninstall [--quiet]",
    "",
    "Support commands:",
    "  agentplane ready <task-id>",
    "  agentplane role <role>",
    "  agentplane agents",
    "  agentplane agent lint",
    "",
    "Task commands:",
    "  agentplane task list",
    "  agentplane task next",
    "  agentplane task search <query>",
    "  agentplane task show <task-id>",
    "  agentplane task new --title <text> --description <text> --priority <low|normal|med|high> --owner <id> --tag <tag> [--tag <tag>...]",
    "  agentplane task add <task-id> [<task-id>...] --title <text> --description <text> --priority <low|normal|med|high> --owner <id> --tag <tag> [--tag <tag>...]",
    "  agentplane task update <task-id> [--title <text>] [--description <text>] [--priority <low|normal|med|high>] [--owner <id>]",
    "  agentplane task scrub --find <text> [--replace <text>] [--dry-run]",
    "  agentplane task scaffold <task-id> [--title <text>] [--overwrite] [--force]",
    "  agentplane task doc set <task-id> --section <name> (--text <text> | --file <path>)",
    "  agentplane task doc show <task-id> [--section <name>]",
    "  agentplane task comment <task-id> --author <id> --body <text>",
    "  agentplane task set-status <task-id> <status>",
    "  agentplane task export",
    "  agentplane task lint",
    "  agentplane task normalize",
    "  agentplane task migrate [--source <path>]",
    "  agentplane task migrate-doc [<task-id> ...] [--all] [--quiet]",
    "",
    "Start commands:",
    "  agentplane start <task-id> --author <id> --body <text> [--commit-from-comment] [--force]",
    "",
    "Block commands:",
    "  agentplane block <task-id> --author <id> --body <text> [--commit-from-comment] [--force]",
    "",
    "Verify commands:",
    "  agentplane verify <task-id> (--ok | --rework) --by <id> --note <text> [--details <text> | --file <path>] [--quiet]",
    "  agentplane task verify <ok|rework> <task-id> --by <id> --note <text> [--details <text> | --file <path>]",
    "",
    "Finish commands:",
    "  agentplane finish <task-id> [<task-id>...] --author <id> --body <text> [--commit-from-comment] [--status-commit]",
    "",
  ].join("\n");
}
