import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import { writeJsonStableIfChanged } from "../shared/write-if-changed.js";

import type { ManifestEntry } from "./ingest-manifest.js";
import { buildSourceSpanSkeleton } from "./source-spans.js";

const CONTEXT_TASK_PACK_FILES = [
  "context-pack.md",
  "canonical-snapshot.json",
  "source-set.lock.json",
  "source-spans.skeleton.jsonl",
  "expected-artifacts.json",
] as const;

async function writeTextIfChanged(filePath: string, text: string): Promise<void> {
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, text, "utf8");
}

function taskRel(taskId: string, fileName: (typeof CONTEXT_TASK_PACK_FILES)[number]): string {
  return `.agentplane/tasks/${taskId}/${fileName}`;
}

function buildExpectedArtifacts(taskId: string): Record<string, unknown> {
  const generatedTaskPackFiles = CONTEXT_TASK_PACK_FILES.filter(
    (fileName) => fileName !== "expected-artifacts.json",
  ).map((fileName) => taskRel(taskId, fileName));
  return {
    version: 1,
    task_id: taskId,
    required: [
      ...generatedTaskPackFiles,
      "context/wiki/glossary.md",
      "context/wiki/reports/coverage.md",
      ".agentplane/context/derived/facts/facts.jsonl",
      ".agentplane/context/derived/graph/entities.jsonl",
      ".agentplane/context/derived/graph/edges.jsonl",
      ".agentplane/context/derived/reports/coverage.jsonl",
    ],
    notes: [
      "Task-bound pack files are CLI-generated scaffolds.",
      "CURATOR owns semantic classification, extraction, topology, wiki synthesis, coverage rows, and evaluator review.",
    ],
  };
}

function buildContextPackMarkdown(opts: {
  taskId: string;
  sources: ManifestEntry[];
  spanCount: number;
}): string {
  const sourceLines = opts.sources.map(
    (source) =>
      `- ${source.path} (${source.status}, ${source.content_type}, ${source.sha256}, ${source.size_bytes} bytes)`,
  );
  return [
    `# Context Pack: ${opts.taskId}`,
    "",
    "This pack is generated by `agentplane context ingest` for a `context.maximum_assimilation` CURATOR task.",
    "",
    "## Required Inputs",
    "",
    "- `source-set.lock.json`: selected source identity, hashes, status, type, and size.",
    "- `canonical-snapshot.json`: current context surfaces available before mutation.",
    "- `source-spans.skeleton.jsonl`: deterministic addressable source spans for semantic classification.",
    "- `expected-artifacts.json`: required output contract for this task.",
    "",
    "## Selected Sources",
    "",
    ...sourceLines,
    "",
    "## Source Span Skeleton",
    "",
    `Generated spans: ${opts.spanCount}.`,
    "",
    "CURATOR must classify spans semantically and produce coverage rows before claiming semantic completeness.",
    "",
  ].join("\n");
}

export async function writeContextTaskPack(opts: {
  root: string;
  taskId: string;
  sources: ManifestEntry[];
  generatedAt?: string;
}): Promise<{ taskDir: string; spanCount: number }> {
  const generatedAt = opts.generatedAt ?? new Date().toISOString();
  const taskDir = path.join(opts.root, ".agentplane", "tasks", opts.taskId);
  await mkdir(taskDir, { recursive: true });

  const spans = await buildSourceSpanSkeleton({ root: opts.root, sources: opts.sources });
  await writeJsonStableIfChanged(path.join(taskDir, "source-set.lock.json"), {
    version: 1,
    task_id: opts.taskId,
    generated_at: generatedAt,
    files: opts.sources,
  });
  await writeJsonStableIfChanged(path.join(taskDir, "canonical-snapshot.json"), {
    version: 1,
    task_id: opts.taskId,
    generated_at: generatedAt,
    surfaces: {
      wiki_root: "context/wiki",
      glossary: "context/wiki/glossary.md",
      facts: ".agentplane/context/derived/facts/facts.jsonl",
      graph_entities: ".agentplane/context/derived/graph/entities.jsonl",
      graph_edges: ".agentplane/context/derived/graph/edges.jsonl",
      coverage: ".agentplane/context/derived/reports/coverage.jsonl",
    },
  });
  await writeTextIfChanged(
    path.join(taskDir, "source-spans.skeleton.jsonl"),
    spans.map((span) => JSON.stringify(span)).join("\n") + (spans.length > 0 ? "\n" : ""),
  );
  await writeJsonStableIfChanged(
    path.join(taskDir, "expected-artifacts.json"),
    buildExpectedArtifacts(opts.taskId),
  );
  await writeTextIfChanged(
    path.join(taskDir, "context-pack.md"),
    buildContextPackMarkdown({
      taskId: opts.taskId,
      sources: opts.sources,
      spanCount: spans.length,
    }),
  );

  return { taskDir, spanCount: spans.length };
}
