export {
  createRepositorySnapshot,
  isGitObjectId,
  isSha256Digest,
  taskCentricDigest,
} from "./digest.js";
export {
  belongsInLiveTaskIndex,
  compatibilityRoleToSemanticWorkKind,
  createLegacyTaskAggregate,
  legacyStatusToTaskLifecycle,
  mapTaskCentricKernelMigration,
  projectTaskLifecycleToLegacyStatus,
  taskCentricAggregateFromExtensions,
  taskCentricReplanRequiredFromExtensions,
  TASK_CENTRIC_EXTENSION_KEY,
  TASK_KERNEL_LIFECYCLE_MIGRATION_VERSION,
  TASK_CENTRIC_REPLAN_REQUIRED_EXTENSION_KEY,
  withTaskCentricAggregate,
  type ArchivedTaskManifest,
  type LiveTaskIndexEntry,
  type TaskCentricKernelMigrationMapping,
  type TaskCentricMigrationFieldMapping,
  type TaskCentricMigrationRuntime,
} from "./compatibility.js";
export {
  approveTaskPlan,
  computeReadyWorkItems,
  createTaskPlanRevision,
  materializeApprovedWorkItems,
  reconcileReplacementPlanWorkItems,
  requiredOutputManifestsPresent,
  requiredOutputsSatisfied,
  resourceClaimsConflict,
  selectSchedulableWorkItems,
  validateTaskPlanProposal,
  validateWorkItemGraph,
  WorkItemScheduler,
  type GraphValidationIssue,
  type ReplacementPlanWorkItemRecoveryEvidence,
  type SchedulableWorkItem,
  type WorkItemReadiness,
} from "./graph.js";
export {
  aggregateValidation,
  assertTaskTransition,
  assertWorkItemTransition,
  decideIndependentReviewApplication,
  evaluateTaskCompletion,
  incompleteRequiredWorkItems,
  requiredWorkItemsComplete,
  type CompletionEvaluation,
  type IndependentReviewApplication,
} from "./lifecycle.js";
export {
  applyPlanRefinement,
  classifyPlanChange,
  consumeRetryBudget,
  createHumanDecisionTicket,
  decideConfirmation,
  dispositionForOutcome,
  recoveryDecisionForFailure,
  validateHumanDecisionAnswer,
  type ConfirmationFacts,
  type PlanChangeClassification,
  type PlanRefinementApplication,
  type SupervisionOutcome,
} from "./policy.js";
export {
  TaskCentricOrchestrator,
  type TaskCentricOrchestratorPorts,
  type TaskLoopOutcome,
} from "./orchestrator.js";
export {
  assertAutonomousRepositoryCapabilities,
  type ArtifactPort,
  type ContentActorPort,
  type ContextPort,
  type GitEffectResult,
  type GitObservation,
  type GitPort,
  type ProviderEffectResult,
  type ProviderObservation,
  type ProviderPort,
  type TaskRepositoryCapabilities,
  type TaskRepositoryPort,
  type ValidationPort,
  type WorkspaceObservation,
  type WorkspacePort,
} from "./ports.js";
export {
  parseTaskPlanProposal,
  REPOSITORY_SNAPSHOT_ZOD_SCHEMA,
  TASK_PLAN_PROPOSAL_ZOD_SCHEMA,
  type ParsedTaskPlanProposal,
} from "./schema.js";
export type * from "./model.js";
